### ISSUE TITLE
Figure out a name for Dimensioned Quantities / Quantities with Units

### ISSUE THREAD

**Issue by szymczdm** [JacquesCarette/literate-scientific-software#102]
For Quantities that **must have** units, we need a name for the new class.

Putting this here so we don't forget.

**Comment by smiths** [comment]
I have done some thinking about this issue and the best that I can come up with is Metrological.  That is, quantities that must have units are Metrological.

Metrology "concerns the establishment of quantity systems, unit systems, units of measurement, the development of new measurement methods, realization of measurement standards, and the transfer of traceability from these standards to users in society." (https://en.wikipedia.org/wiki/Metrology)

In my brainstorming, I also considered Dimensioned, Dimensional, and Measured.  I think these terms would be confusing, since dimensions often refer the dimension of the problem (1D versus 2D versus 3d etc), and even though quantities with units can be measured (at least indirectly), they won't always be measured for the software, but sometimes calculated.

If we don't like Metrological (or the other choices listed above), then I don't think there is an existing word that will do the job for us.  We'll need to create a term for a quantity with units.  We could use something like Elamed (in honour of one of the first known system of weights and measures in Persia), or Levitical (in honour of the biblical commandment to be honest and have fair measures).  The last two ideas come from the history of measurement (https://en.wikipedia.org/wiki/Units_of_measurement).  From (https://en.wikipedia.org/wiki/History_of_measurement) we could use Carob, since one of the first units of volume was to count carob seeds.  (Apparently that is where carat comes from.)

I could keep going with ideas like this, but I'd like opinions on Metrological before I start getting too silly.  :-)

**Comment by JacquesCarette** [comment]
Excellent investigation.  That caused me to think deeper about it too (because, although I don't dislike `Metrological`, it is quite a mouthful).  So I started looking around and found http://www.macmillandictionary.com/thesaurus-category/british/describing-or-relating-to-units-of-measurement.  Which brought to mind `Unitary`, and that I quite like!

**Comment by smiths** [comment]
Unitary sounds good to me!  (I agree that Metrological is quite a mouthful.)  :-)

**Comment by szymczdm** [comment]
We've figured out a name. I've added an issue for implementing unitary chunks #161, so I think this issue is closed.
