### ISSUE TITLE
Fix the GlassBR example

### ISSUE THREAD

**Issue by szymczdm** [JacquesCarette/literate-scientific-software#113]
There is a lot of fairly mechanical work to be done on GlassBR. Namely, reducing the number of duplicate chunks, as there are multiple chunks for the same terms/concepts/etc.

Mentioned in commit 3b26d0ca8014b and you can see a few examples of what's wrong there.

**Comment by szymczdm** [comment]
There is also inconsistency with the naming conventions which I'm dealing with now. We should agree on either referring to it as "GlassBR" throughout the documents, or "Glass-BR". Currently both are used.

**Comment by smiths** [comment]
Hi Dan.  I agree with the need for consistency.  Between the two options, I do not really have a preference.  If I had to decide, I would pick GlassBR.

**Comment by szymczdm** [comment]
Just wanted to add, this will be an ongoing task over the summer, but we should get the first pass done soon.

**Comment by niazim3** [comment]
Update: commit ddefd15

**Comment by niazim3** [comment]
@szymczdm @smiths 
I'm looking through GlassBR's Example.hs file, and cannot seem to find much duplication... perhaps I'm not looking through the file correctly? Would it be possible to see an example of what I'm supposed to fix so that I know I'm going in the correct direction?

**Comment by szymczdm** [comment]
This one requires a deeper look at the existing chunks. Just taking a quick glance, I saw two different "non-factored load" chunks which are completely unrelated from each other (`nonFactorL` and `nfl`). If anything, one of those should be built from the other.

This may not be possible right now (because of the current implementation of data structures), but that's something we should find out sooner than later, since it may mean just updating a few constructors and a data type.

**Comment by niazim3** [comment]
Looking at the duplication of the term/concept of "non-factored load" via the use of nonFL, nfl, and nonFL, I was able to get rid of nonFactorL (however with small discrepancies still occurring) so now nonFL is defined:
`nonFL :: QDefinition
nonFL = fromEqn' "nonFactorL" (cn' "Non-Factored Load") (Atomic "NFL") nonFL_eq`
Unfortunately, I am running into some difficulties when I am attempting to merge nfl (ConceptChunk) and nonFL(QDefinition) into one chunk... since the definition of non-factored load is defined and used from nfl and there doesn't seem to be a parameteR QDefinition can take for the definition of a term,

**Comment by niazim3** [comment]
Note to self:

The following terms seem to have duplicates:

- `nonFL` **(QDefinition)** and `nfl` _(ConceptChunk)_ and `nonFactorL` (CINP)
- `ar_max` (VarChunk) and `aspectRMax` (CINP)
- `eqTNT` (CINP) and `tNT` (VarChunk)
- `lResistance` (CINP) and `lRe` (VarChunk) and `lr` _(ConceptChunk)_
- `loadSF` (VarChunk) and `lShareFac` (CINP) and `lsf` _(ConceptChunk)_
- `ar` (VarChunk) and `aspectR` (CINP) and `aR` _(ConceptChunk)_
- `an` _(ConceptChunk)_ and `annealedGlass` (CINP)
- `heatSGlass` (CINP) and `hs` _(ConceptChunk)_
- `glassTypeFac` (CINP) and `gTF` (VarChunk) and `gtf` _(ConceptChunk)_
- `pb` _(ConceptChunk)_ and `prob_br` (VarChunk)
- `sd` (UnitalChunk) and `sD` _(ConceptChunk)_
- `lDurFac` (CINP) and `loadDF` **(QDefinition)**

**Comment by niazim3** [comment]
Update:
- `eqTNT` and `tNT` cannot merge due to presence of "trinitrotoluene" in `eqTNT`... are different terms so there is no need to remove
- in order to completely remove `gTF`, `loadSF` and `lRe`, need to figure out how to/if can use a _CINP_ in an expression and/or relation (specifically in 
`dL_eq :: **Expr**
dL_eq = ((C demand):*((Grouping ((C plate_len):*(C plate_width))):^(Int 2))) :/((C mod_elas):*((C act_thick):^(Int 4)):*(C **gTF**))`
and in
`cap_rel :: **Relation**
cap_rel = (C **lRe**) := ((C nonFL):*(C glaTyFac):*(C **loadSF**))
`
and in
`safety_require2_rel :: **Relation**
safety_require2_rel = (C is_safe2) := (C **lRe**) :> (C demand)
`)

In general, most of the duplications between _CINP_ and _VarChunk_ types have reduced.

**Comment by niazim3** [comment]
- The _ConceptChunk_s are called when **term**s, **definition**s, and **getAcc** are needed and the _CINP_ type of a term is called when the **short** of a term is needed, which is why `heatSGlass`/`hs`, `lResistance`/`lr`, `glassTypeFac`/`gtf`, `lShareFac`/`lsf`, `aspectR`/`aR` and `annealedGlass`/`an` are duplicated.
- The same goes for `pb`/`prob_br` (where `pb` is used underneath "Terms" and `prob_br` is used as a Unitless chunk underneath "Table of Symbols")
- `sD` could potentially be removed however, GlassBR's document requires 1 of 2 different definitions when called (i.e. "Stand off distance which is represented in coordinates (SDx, SDy, SDz)" and "The distance from the glazing surface to the centroid of a hemispherical high explosive charge")
- `loadDF` is used in DataDefns and `lDurFac` is used in Acronyms, both of which require different types, so those terms cannot be merged either...

@szymczdm Other than merging the similar chunks, can anything else be done to reduce duplication?

**Comment by smiths** [comment]
Hello Maryyam.  The two definitions of sD are consistent with one another.  Could you combine them into one definition?  "The stand off distance is the distance from the glazing surface to the centroid of a hemispherical high explosive charge.  It is represented by the coordinates (SDx, SDy, SDz)."  I haven't looked to see where sD is used, so maybe having two sentences doesn't work grammatically.

**Comment by niazim3** [comment]
@smiths Sure, I'll merge the 2 sentences into 1 definition. 
However, this brings up the question of what would be preferred as an output next to **SD** because in the Table of Symbols right now it is
![image](https://cloud.githubusercontent.com/assets/28247301/26209637/5ae3aa50-3bbb-11e7-8520-9c3ab5d78e19.png).
Would you like me to update stable so that under the description column it simply states "Stand off distance"? Or would that be straying away from the desired output?

**Comment by smiths** [comment]
Hello Maryyam.  Yes, I like your idea that the table will just call SD "Stand off distance."  This would make it consistent with the other definitions.  Yes, I think it makes sense to update stable to this new table.

**Comment by niazim3** [comment]
**GlassBR.Concepts.hs** currently has only one concept in it.
Would it be better to pull out concepts from GlassBR.Example.hs into GlassBR.Concepts.hs for organization purposes, or pull out the one ConceptChunk into another file so that there isn't an additional import?

**Comment by szymczdm** [comment]
Sorry for the delay, this flew under my radar somehow.

I'd say it'd be better to do the former (for organization purposes).

**Comment by JacquesCarette** [comment]
Yes, pull from Example into Concepts.  Though it is fine to have small files.  If there is only one new concept in an example, then having a Concepts file with just one definition is fine.

**Comment by niazim3** [comment]
Thanks; looking through the other examples, there is either an Example.hs file, Concepts.hs, or neither, which is why I was wondering what exactly differentiates an example from a concept? Generality, use of symbols, chunks being built off of others? Or is it up to one's judgment?

**Comment by niazim3** [comment]
I believe duplication has been removed as of commit def206a.

**Comment by niazim3** [comment]
@JacquesCarette mentioned that in **Unitals.hs**, there are "a lot of concepts (words) which are repeated.  It feels like this should be more 'compositional'". Reopening this issue to help keep track of what changes will be made to files and because this seems to be related to the original duplication that needed to be removed.

**Comment by niazim3** [comment]
I believe this issue can be closed as of commit 0f9e7db,
