### ISSUE TITLE
See how "Melting", "Boiling", etc. are used throughout the example docs and form a design plan

### ISSUE THREAD

**Issue by szymczdm** [JacquesCarette/literate-scientific-software#116]
I'm going to start going over the examples and their documentation to see how the verbs/adjectives are used throughout. Then we should form a plan on what to do/how to incorporate them.

**Comment by szymczdm** [comment]
Taking a look at "melting" in the examples presently. Here's what I found (this is the use of the "melting" chunk in our example, "melting" actually comes up in a number of other places but is not pulled from the chunk). Overall, there is no use of the definition ("Phase change from solid to liquid") anywhere.

### SWHS
    A17: The volume change of the PCM due to **melting** is negligible [IM2]

In the derivation of an equation:
Although a small change in surface area would be expected with **melting**, this is not included since the volume change of the PCM with **melting** ...

R11: Calculate and output the time at which the PCM stops **melting** t_melt^final (from IM2)

###HGHC

It comes up once, not from a chunk however, and if only used in a module.

**Comment by JacquesCarette** [comment]
So **melting**, as used in SWHS, seems to describe a process.  Above, *melting* does not seem to be used as either a verb or an adjective!  What is it?

**Comment by szymczdm** [comment]
It's used as a verb in several locations, but also as an adjective (there are a few instances where it's used as "melting point"), though that's also different chunk. It's definitely context dependent.

**Comment by JacquesCarette** [comment]
So I think that that correspond to two different notions of 'melting'; they are related, of course, but not identical.  It is a coincidence that their English rendering is identical.  In other languages, both natural and 'programming', they may end up denoting something different!

**Comment by szymczdm** [comment]
Yup, boiling is used similarly, either in "boiling point" or "boiling of the...". Again though, the chunk "boiling" is only used for the verb, whereas other chunks have it used as an adjective (ex. temp_boil)

**Comment by szymczdm** [comment]
We also have chunks for charging/discharging in SWHS. They are used exclusively as verbs, except for the definitions which are used in place of "(dis)charging of the tank".

Clearly these two should not be nounphrases.

**Comment by smiths** [comment]
I'm all for a deeper understanding of our documentation, but are we going too far here?  I don't see what likely change we are identifying.  I'm worried that when this is sorted out we will have a complicated way of simply saying melting.  It isn't like this is a concept that will change, at least not in the PCM example.

Thinking about it further, I can see one variability.  Maybe the SRS author could opt to replace the term melting with the definition "phase change from solid to liquid."  In Dan's examples above we could make this substitution and the sentence reads fine.  I prefer using the word "melting" and letting the reader look up the definition, if they need it.

Maybe we are looking for a physical definition of melting?  Melting occurs when the temperature exceeds the melting point and melting continues, without a temperature change, as long as energy is added and there is unmelted material present.  This idea is expressed through the equations in the document.  Maybe we should be focusing our energy on the equations instead of the English text?

**Comment by JacquesCarette** [comment]
So I think that a good middle ground is to focus on those concepts which occur as part of the things which are of class `Quantity`.  We can punt on those which are more complex than that.

Though I do think (going back a few comments) that boiling does occur (`temp_boiling` above).  So we do need to 'understand' how to deal with that appropriately.

**Comment by szymczdm** [comment]
I believe in our discussions the design plan ended up being the "modifiers" for nounphrase (see #129). So I'm closing this issue, if the implementation does not end up being straightforward, I'll reopen this and we can discuss a more in-depth design. It seems like it should be fairly straightforward, however.
