### ISSUE TITLE
Text with emphasis within Sentences

### ISSUE THREAD

**Issue by bmaclach** [JacquesCarette/literate-scientific-software#12]
As discussed in the meeting on May 25th, there is currently no way to add emphasis to text within Sentences (i.e. boldface, italics).

**Comment by JacquesCarette** [comment]
I've assigned this to myself as a proxy to mean "this needs a design".  We need to figure out what this means, so that it can be 'rendered' properly in different formats.

**Comment by JacquesCarette** [comment]
I'm still a little bit stuck on this one.  It is very obvious how we want things to be rendered, but what we'd like in the input is something more semantic.  So what does emphasis mean?  What are we trying to do when we use emphases?  The tricky part is that we may well end up using the same markup (bold, say) to mean more than one thing.  But first, we need a list of those things!

**Comment by smiths** [comment]
I spent a bit of time googling the purpose of italics and bold in writing.  Although not entirely satisfying, the following web-page has lists of reasons for using italics and bold:

http://jadevarden.blogspot.ca/2012/05/writing-101-using-italics-bold-and-in.html

This list is for fiction writers.  Only two reasons stand out for me: emphasis and foreign words.  For instance there are some Latin phrases that we might use that should be italicized, but the common ones (like et al, a priori, etc, etc (the second etc is on purpose)  :-) ) are not italicized.  For words that really should be italicized, like say raison d'etre, I think we could define them as a chunk and render them as appropriate.  Maybe there would be a new foreign word type of chunk?

Emphasis is tougher, since it is a writing choice.  The simple solution is to just not allow emphasis.  I almost never use italics or bold in my own writing, so I wouldn't really miss not being able to do it.  It certainly would be the simpler solution.  All of the writing guidelines I looked at suggested minimizing italics and bold.  If we don't allow it at all, we definitely have a minimum.  :-)  

I think if a concept is emphasized every time that it is mentioned, we could have a chunk type for this.  An "emphasized concept" might be bold every time it is rendered.  However, in writing we often emphasize the first occurrence and not subsequent ones.  I supposed we could have a rule for the document that enforces this.

In the short term, my vote is to simply not allow italics and bold.  We can return to this question as we amass more examples.

**Comment by JacquesCarette** [comment]
Great sleuthing.

So I only see a single use for emphasis that we ought to support sooner rather than later: definitions.  We might want different means of defining things, where the word/concept we are defining is emphasized from its surrounding text.

Should we close this issue (but move a reference to it to the wiki first)?

**Comment by smiths** [comment]
I agree that we might want to emphasize definitions.  I've added a list of issues we want to return to in our wiki.  I agree that we should close this issue for now.

**Comment by samm82** [comment]
There is an example of the use of emphasis in caseStudies in #827.
