### ISSUE TITLE
Double check your use of "for" combinators

### ISSUE THREAD

**Issue by szymczdm** [JacquesCarette/literate-scientific-software#142]
Hey all,

Can you just double check that anywhere you use one of the for combinators, the output is still as expected? I've modified how they work so for and for' are the only implicit combinators, and for'' takes two functions as arguments (i.e. two of: `titleize`, `phrase`, `plural`, `at_start`) and then applies them to the first and second term respectively.

I've also updated mkDoc' so that it can take a combinator instead of implicitly using one of the variations of `for`. So to specify using `for'` for instance you would do:
`mkDoc' mkSRS for' thisSI`
where mkSRS and thisSI are your DocDesc and SystemInformation respectively.

Once I'm sure it's all working properly, we can close this issue.

- [x] gamephys
- [x] glassbr
- [x] pcm
- [x] ssp
- [x] swhs
- [x] tiny

**Comment by hmadej** [comment]
changes to for' matches output for stable for gamephys

**Comment by njericha** [comment]
this did not have any effect on SSP that I can tell

**Comment by danscime** [comment]
Did not seem to effect SWHS

**Comment by niazim3** [comment]
I'm running into a problem since GlassBR needs to _titleize_ the first term and _phrase_ the other... that is because the **glassBR_srs'** function doesn't have the information to fill the parameters **t1** and **t2** from where it's called. I tried 
glassBR_srs' = mkDoc' mkSRS (for'' titleize phrase _ _) glassSystInfo
, but the _ _ aren't receiving anything so I get an error...

**Comment by szymczdm** [comment]
@niazim3 try removing the _ _ and just have `for'' titleize phrase`, thanks to Currying, the function will then have the right type signature and should be passed in just fine.

**Comment by niazim3** [comment]
GlassBR updated as of f5d0aef.
