### ISSUE TITLE
More Definition Questions

### ISSUE THREAD

**Issue by AKM11** [JacquesCarette/literate-scientific-software#163]
Two quick questions, first, in PCM Example, what is `t1descr` (not sure how I am supposed to 'complete' the definition, also, do I need to rename it?) and second, how am I supposed to define `heat` (noun or verb or both)?  Trying to clear issue #93.

**Comment by smiths** [comment]
The full text for the description of T1 (theoretical model for the conservation of thermal energy) is given in the Case Studies folder of our literate-scientific-software repo.  (The same material is also available at https://github.com/smiths/swhs/tree/master/SRS.)  Your version is incomplete.  I believe this is because @szymczdm was planning on auto generating parts of the description from the equation.

As far as heat goes, it can be both a verb and a noun.  @szymczdm would know whether this is supported yet by Drasil, but I could see defining it for both.  The verb heat means to transfer thermal energy to a body.  The noun heat refers to the heat energy inside a body.  I just did a quick google search, and I like the following definition of the noun heat: 

Heat energy (or thermal energy or simply heat) is defined as a form of energy which transfers among particles in a substance (or system) by means of kinetic energy of those particles. In other words, under kinetic theory, the heat is transferred by particles bouncing into each other.  (from https://www.thoughtco.com/heat-energy-definition-and-examples-2698981).

Maybe our definition should be for heat energy, and heat is simply a short form for heat energy?  @szymczdm, would it be possible to define heat energy and make its abbreviation simply heat?

@AKM11, please split your issues into atomic pieces.  This issue now discussed t1descr and heat.  We should have one topic per issue.

**Comment by AKM11** [comment]
Alright, thank you Dr. Smith.
