### ISSUE TITLE
Moving common modules to data/drasil/modules.hs

### ISSUE THREAD

**Issue by hmadej** [JacquesCarette/literate-scientific-software#187]
data/drasil/modules.hs has been created, common modules should be added to it and removed from specific examples. 

We will need to add the following imports to any files affected by the move 
`import Data.Drasil.Modules`

and remove any common modules from our specific examples.

- [x] gamephys
- [x] glassBR
- [x] pcm
- [x] ssp
- [x] SWHS
- [ ] tiny

**Comment by njericha** [comment]
The rest of my modules are all specific to slope stability but could possibly share similar formats

**Comment by AKM11** [comment]
Module file not present in PCM.

**Comment by niazim3** [comment]
Tiny has been updated as of commits 9cb4901 ... 533c4f0.
`mod_inputp` doesn't call `mod_io_fun` despite having similar content due to it having 1 less parameter than what is required by the general `mod_io_fun` _ModuleChunk_. 
@szymczdm there are multiple `meth_` _MethodChunk_s that weren't pulled since they are specific to tiny.
Overall, I believe this issue can be closed.
