### ISSUE TITLE
Manually create the compound phrase, because it uses acronym and a sentence.

### ISSUE THREAD

**Issue by danscime** [JacquesCarette/literate-scientific-software#207]
The last FIXME in SWHS Concepts.hs

"Temporarily have to manually create the compound phrase, because it uses acronym and a sentence."

Not sure exactly what it means but Dan said it needs to be a separate issue.

**Comment by njericha** [comment]
This issue is about the following line in `Concepts.hs`,
```
swhsProg = npnc' "swhsProg" (nounPhrase'' (short progName +:+
  phrase program) (short progName +:+ phrase program)
  CapFirst CapWords) "SWHS"
```
There should be a way to create this NamedChunk by compounding progName and program. I just thought of a better fix.

**Comment by njericha** [comment]
Tried another method to grab the term in `compoundPhrase'''` rather than `compoundNC'''` but did not work. Got circular imports between NounPhrase.hs and NamedIdea.hs.

**Comment by szymczdm** [comment]
After looking into this, it seems it was an issue with having the "correct" smart constructor for this particular case. Either way, it seems to have been a one-off that was only being used for the module guide of SWHS and as of 7717e5a it no longer exists.

I'm going to close this issue, since it really is unclear to me what the exact problem was, and should it come up again in the future we'll tackle it then.
