### ISSUE TITLE
Automated Paragraphs Completion

### ISSUE THREAD

**Issue by AKM11** [JacquesCarette/literate-scientific-software#212]
We have started to add some generalized versions of a few paragraphs to Example\Drasil\OrganizationOfSRS.hs.  Try to implement them into your codes where possible.  If you see any other commonalities, add them to OrganizationOfSRS.hs. Thanks.

- [ ] GamePhysics
- [ ] GlassBR
- [ ] HGHC
- [ ] NoPCM
- [ ] SSP
- [ ] SWHS

Also, if you create a new paragraph-function, feel free to let everyone know on this thread so they can implement it.

**Comment by AKM11** [comment]
The _introductions_ for **General Systems Description** and **Specific System Description** have been created.

**Comment by JacquesCarette** [comment]
Thanks.

Note that issues are best when they are focused, and can be closed 'soon'.  For documenting new paragraph functions, it might be best to use the Wiki or Projects feature of github, rather than Issues.  There are also other features of github we might be able to use for this (there are tons which can be enabled).

**Comment by AKM11** [comment]
Okay, created a project, anyone who makes a new generalized paragraph can mention it there.

**Comment by njericha** [comment]
See this project https://github.com/JacquesCarette/literate-scientific-software/projects/1
I imagine we will just make individual issues for each implementation of a "section function" or just refer to this project.
