### ISSUE TITLE
New Section "Characteristics of an Intended Reader" for GlassBR

### ISSUE THREAD

**Issue by niazim3** [JacquesCarette/literate-scientific-software#237]
(Related to Issue #230) 

In terms of content, how is the following paragraph for the added section "Characteristics of an Intended Reader" for GlassBR? @smiths 

"Reviewers of this documentation should have a strong knowledge in theory behind glass breakage and blast risk. The reviewers should also have an understanding of second year calculus, structural mechanics, and computer applications in civil engineering. The users of GlassBR can have a lower level of expertise, as explained in _this Section_." (where the reference takes the user to the **User Characteristics** section)

**Comment by smiths** [comment]
Sounds good.  The only thing I would add is an explicit statement that the reviewer should be familiar with the applicable standards.  We should then cite the standards that are used for the source material for the SRS.  If you can add this information, then we can close this issue.

**Comment by niazim3** [comment]
Thanks for the feedback @smiths . Is the following an improvement?
Also is this specific to GlassBR or is this addition applicable to all examples (in which case the generalized function will need to be alterred)?

"Reviewers of this documentation should have a strong knowledge in theory behind glass breakage and blast risk. The reviewers should also have an understanding of second year calculus, structural mechanics, and computer applications in civil engineering. The users of GlassBR can have a lower level of expertise, as explained in _this Section_." ++ **"The reviewer should also be familiar with the applicable standards from _this Section_."** (where **_this Section_** takes the user to the References section)

**Comment by smiths** [comment]
The addition of referencing the applicable standards only applies to GlassBr.  There aren't any standards to reference for the other projects.

I would prefer the pointer to the standards appears with the text on the reviewer requirements, rather than after the text about regular users.  I also think we should just reference the standards, not all of the references in the References section.  Reviewers of the document don't need to be familiar with Smith and Lai (2005) for instance.  My specific recommendations are as follows:

"Reviewers of this documentation should have a strong knowledge in theory behind glass breakage and blast risk. The reviewers should also have an understanding of second year calculus, structural mechanics, and computer applications in civil engineering.  In addition, reviewers should be familiar with the applicable standards for constructions using glass [4--6].  The users of GlassBR can have a lower level of expertise, as explained in this Section."

**Comment by niazim3** [comment]
Thanks again for the feedback.
Implemented as of commit 9839e25.
