### ISSUE TITLE
GlassBR Goal Statements Intro

### ISSUE THREAD

**Issue by niazim3** [JacquesCarette/literate-scientific-software#252]
GlassBR currently has the following in the CaseStudies pdf for the **Goal Statements** section: 
![image](https://cloud.githubusercontent.com/assets/28247301/26832255/e0f204b2-4a9c-11e7-90d6-192eb833605a.png)

However, the rest of the examples have a generalized statement before the GSs are listed: "Given _______, the goal statements are:", where ______ is a list of inputs (e.g. for SWHS it is "the temperature of the coil, initial temperature of the water and material properties").

What are the inputs that GlassBR needs to complete the above-stated goal statement? @smiths

**Comment by smiths** [comment]
Hello Maryyam.  I agree that the goal statement would be improved by a summary of the inputs.  The original goal statement was trying to be abstract, but it is more abstract than necessary.  I like your idea better.  However, I'm hesitant to answer your question, since the information you are seeking should be easy to find in the SRS.  (If it isn't easy to find, than the SRS needs to be improved.)  @niazim3, could you try to answer your own question and I'll let you know if I think your answer is correct?  (I'm not testing you; I'm testing the documentation.)  😄

**Comment by niazim3** [comment]
Thanks for the feedback @smiths.
I believe the following may be it, but please do let me know if I'm missing any of the inputs:
"Given **the glass type and characteristics of the explosion**, the goal statements are ..."

**Comment by smiths** [comment]
Thank you @niazim3.  Unfortunately, the document failed the test.  I would list the inputs as the dimensions of the glass pane, glass type, characteristics of the explosion and the tolerable probability of breakage.  (You were missing the dimensions of the glass plane and the probability of breakage.)  I found this information in Section 5.2 in Use Case 1, although in re-reading it, this section could certainly be improved.  For instance, the response type is listed as an input, but in A7 the response type is included as an assumption.  The user does not select this.  The documentation of use cases doesn't really fit either, since the program only has one use case, not two.  The use case is the user enters the inputs and the user gets the output.  Input and output are not separate use cases.  For now, focus on the goal statement, but in the future I would like to return to the question of revising Section 5.2.

The inputs for GlassBR are also given in Table 2 (Input Variables).

**Comment by niazim3** [comment]
GlassBR updated as of commit 828d0b3.
In order to close this issue, created issue #257
