### ISSUE TITLE
Test Documentation for GlassBR

### ISSUE THREAD

**Issue by niazim3** [JacquesCarette/literate-scientific-software#262]
What is the intended difference between the `Python` and `Python_Simplified` directories? For the most part, their files are quite similar, however upon 'make testing' them, there are far more failures resulting when making from the `Python_Simplified` folder... is one meant to replace the other? @palmerst
Which one should I be focusing on in terms of looking through the test cases? @szymczdm 
Edit: From what I understand, the output from making `Python` is the desired result:
![image](https://user-images.githubusercontent.com/28247301/26886889-9d4f83fa-4b74-11e7-8996-e2d0edce9a0b.png)

**Comment by szymczdm** [comment]
I believe you should be focusing on Python, but if @palmerst is using Python_Simplified in the GOOL/code gen side of things, we may want to look at that as well.

**Comment by palmerst** [comment]
Python_Simplified is what is being used for gool/code generation.  Maybe it should actually be called "Python_Improved".   Some tests fail because I didn't modify the testing as I updated the code.  The code is correct, it is the tests that are not.  

The testing needs a lot of improvement -- there is huge amount of repeated code (each test suite has 5-10 source files which are just complete copies of each other with different hardcoded inputs).   Since I made changes to the function signatures, in its current form this would require changing every single copy of each affected test suite, which is why I didn't update it.

**Comment by smiths** [comment]
@niazim3 , when you are looking to understand the test cases the Python folder is a better starting point.  Once you understand the tests though, it would definitely make sense to improve things along the lines that @palmerst has suggested.  The tests that were built last summer were very naive in how they were set up.  We can do better.  You can first focus on what is being tests, and later we can look at a better way to actually test it.

**Comment by niazim3** [comment]
@smiths @szymczdm Would it be possible to get some feedback as to whether this is what I should be doing when trying to document how the tests are understood?
![image](https://user-images.githubusercontent.com/28247301/26892120-44065d4e-4b85-11e7-9758-08f77dd9c422.png)

**Comment by szymczdm** [comment]
That looks pretty good. The only thing I'd add is traceability to where that test came from (in the theory). For example when testing if some `a > 0`, what is that `a` and why must it be `> 0`, where in the theory is that constraint? If it's an assumption, constraint, one case in an equation, etc. that should be made clear.

**Comment by smiths** [comment]
Thank you for taking the initiative on this @niazim3.  I agree with @szymczdm that you are off to a good start.  I also agree that traceability would be nice.  Unfortunately the additional data that I would like for each test case will make it difficult to summarize it in your table, since you would have to add several wide columns.

For each test case, I would like the following additional information (in addition to what you and Dan already have):

1. Test name
2. Test purpose (I think you have that in your Testing ... column)
3. Inputs (in some cases initial state would also be relevant, but I don't think that applies for your tests)
4. Expected outputs
5. Notes - in some cases we might need extra room to explain something else about the tests, like the rationale, the motivation, the source of the information, the derivation of the closed form solution, etc.

You can see an example of this in the V&V Plan for SWHS:

https://github.com/smiths/swhs/tree/master/VVPlan

Although @JacquesCarette is correct that we do not want to write a V&V plan at this time, we do want to capture the key information on the tests that would be included in that plan.  In particular, the tables in the plan (like Table 1) show summaries of the input and the expected output for the tests.

Once we have settled on a template for summarizing the tests, we can explicitly assign this issue to your colleagues as well.

**Comment by niazim3** [comment]
Clarification request: the test name is the same as the file name, correct? @smiths

**Comment by smiths** [comment]
Great question @niazim3 .  I'm glad that you asked.

No, the test name and the file name do not have to be the same.  The existing test cases suggest this, but the existing testing code makes two debatable choices:

1. There is essentially one test case per file.  This really isn't necessary.  A single file can have multiple unit tests.

2. The filenames are essentially meaningless.  Test1, Test2, etc are not helpful names.  TstValidInput_Dimensions, or Tst_Pb_ExtremeValues etc, would be much more helpful names.  The name should be a mnemonic that gives a hint as to what the test does.  I think you will have to make up names; I do not believe this information is in the files that you are starting from.

**Comment by niazim3** [comment]
Will be keeping track of which main folder is completed thus far using the following:

- [ ] testCalculations
- [ ] testCheckConstraints
- [ ] testDerivedValues
- [ ] testInputFormat
- [ ] testInterp
- [ ] testMainfun
- [ ] testOutputFormat
- [ ] testReadTable

I'll upload the completed document once this list is checked off.

**Comment by smiths** [comment]
Sounds good. My only additional request is that you don't wait until the end to upload your document. Please take advantage of version control and commit and push as each section is done or edited.

**Comment by niazim3** [comment]
Added new document to track as of commit 918f385.
So currently, there should be an updated version of the word document in everyone's working directories; however, since the file type is of `.docx`, I'm not sure whether or not the changes can be viewed as I edit the document, which is why I think the file type may have to be changed soon. Is there a preferred file type to implement this data in?

**Comment by smiths** [comment]
The preference for reports is to use LaTeX.  This way when you make changes to the document, we can see the difference, just like we can with code.  You are correct that this isn't possible for binary files, like a docx file.  I think learning LaTeX would be a great skill for you and your colleagues to add to your resumes.  You can look at existing LaTeX documents as a guide, although you should probably look at the human generated files, rather than the drasil generated files.  @hmadej would be able to assist you with getting started.

**Comment by niazim3** [comment]
Update: majority of the test case information has been recorded as of commit 65c57fe. 
Note to self: The **?** entries indicate items to be inserted; table 8 and table 5 need to be looked at in more depth.

**Comment by niazim3** [comment]
@palmerst 
The results from making the `Python` tests have changed quite drastically, and I was wondering if some changes were made that caused the discrepancy?
![image](https://user-images.githubusercontent.com/28247301/28074127-c96b5d12-6625-11e7-96d4-949940d1c178.png)
I'm attempting to trace the failing files that were previously `pass`ing so that I can ensure working on issue #347 doesn't change anything it is not supposed to.

**Comment by palmerst** [comment]
These errors are being caused from the change to reading the input variable `t` as a string.  When readline is called on a file, the resulting string is stored with a newline char at the end of it.  So for example if the input file has 10.0 for t, it will be read as "10.0\n" and will not be equal to the string "10.0".  You can fix this by using readline().rstrip() instead, as this will strip all whitespace from the beginning and end of the string.

**Comment by niazim3** [comment]
9aed9dc -->
![image](https://user-images.githubusercontent.com/28247301/28090394-13c2fec2-665a-11e7-8cf7-45d1c5c8f635.png)
Less tests fail now, however I will be working on getting all the tests to pass soon. (Completing said task will now be documented in issue #347, as this thread is for testing documentation...)

@palmerst Would it be alright if I remove _testCheckConstraints18.py_ from the `Python` directory (as it is the exact same as _testCheckConstraints17.py_)? If so, should I also be removing it from the `Python_Simplified` directory?

**Comment by palmerst** [comment]
Yes, remove it.  `Python_Simplified` is the version that is being used as a benchmark for generation.  You can actually delete the `Python` directory entirely and rename `Python_Simplified` to `Python`  -- I kept both as I was rewriting the original to be more readable, but now there is no sense in maintaining both.

**Comment by niazim3** [comment]
The **TestDocumentation** folder that contains the test document is now in the _Python\_Simplified_ directory. However, since making the tests from this directory currently runs into errors, I'm in the process of rooting out the problem. As stated before, updating/improving the testing for GlassBR will be tracked in issue #347.
