### ISSUE TITLE
Make-shift Values?

### ISSUE THREAD

**Issue by AKM11** [JacquesCarette/literate-scientific-software#263]
The last failing test cases for No-PCM seems to be the result of a lack of information.  The .out files for the Matlab and C code example  calculations (found in SolarHeatingWaterOnly\Python\Testing\compareMatlab and compareC specifically) lack a No-PCM energy/temperature section, making the last two failures more problematic to deal with as the information needed simply does not exist. 
To this end, I suggest using the '_total energy_' section for the PCM example as the '_energy of no-pcm water_', and using this value to manually calculate '_temperature of water_'. This method will not be completely accurate and is definitely cheating so I wanted to check with someone first.  Should I go with this method to get all the test cases working or can anyone think of another way on how to approach this problem?  Is there a way to regenerate the .out files with the needed information?

**Comment by smiths** [comment]
If I understand what you are trying to reproduce, it is the test cases where the output of your program is compared to the output of another independent program.  This was an option for SWHS, but is isn't actually currently an option for you, because we don't have another program that calculates the noPCM outputs.  The easiest, and valid, solution is to just drop these test cases.  There is no point comparing to output files that are based on a different mathematical model.  If you really want to keep these examples, you would have to modify the original FORTRAN program so that it also solves for noPCM.  This would be easy to do, but it wouldn't really add anything to our confidence in your program.  If you code agrees with the closed form solution, then agreeing with another program is redundant information.

If I misrepresented what you are trying to do, please let me know.

**Comment by AKM11** [comment]
You understood what I was asking, thank you, I will remove the Matlab and C comparison tests.  As a side note however, the FORTRAN code actually included useable no-pcm calculations in its output, it was just the Matlab and C code that were missing this information.

**Comment by smiths** [comment]
Sounds great.  Please keep the FORTRAN comparison.  It doesn't add new information, but it isn't wrong to have it either.  Since the work was done, we might as well benefit from it.  😄
