### ISSUE TITLE
Questions about redefining defining spaces

### ISSUE THREAD

**Issue by njericha** [JacquesCarette/literate-scientific-software#266]
There are a few questions we have about being explicit with these spaces. How should we design quantities that are defined in Data.Drasil.Quanities? For example,
```
stffness :: UnitalChunk
stffness = uc CSM.stffness cK stiffnessU
```
Since `uc` implies `Rational` and my example uses a `Float` I would need to change this type. The issue with this is that any other future examples would be forced into coding with `stffness` being a `Float` when they might want it to be `Rational` or `Int`.

Secondly, what should we say for quantities that are `Float` in some equations but `Vector` in others?

**Comment by hmadej** [comment]
do spaces relate to mathematical spaces? do we differentiate between Natural Numbers vs Integers? should we define an R^1 R^2 ... R^n space? Bool^N etc?

**Comment by smiths** [comment]
Yes, spaces are mathematical spaces.  The space of a variable is its type.  All of the examples @hmadej listed could come up.  Our approach should be to add new types as required.  As for the original question from @njericha, we don't want Float to be a type that appears in our requirements documentation.  In the implementation we will use Float to approximate a real number.  We could use another choice to approximate the real number, so we don't want to constrain the design too early.  With respect to stiffness, it should be a real number, because that's what physics tells us.  If in some future application the stiffness should happen to have an integer value, it is still a value from the set of reals.

Quantities are vectors if that is there type.  The type of a vector might be R^n, where n is the length of the vector.  A position vector in 3D space would have type R^3, while each position coordinate would have type R.

**Comment by JacquesCarette** [comment]
And to be precise: we need a `Real` Space -- and most uses of `Rational` should be `Real`.  We might not be able to use `Real` as the word, since that may conflict with Haskell, but something like it.

**Comment by njericha** [comment]
So the `Space` of these quantities defined in Data.hs should reflect physical reality rather than how they would be measured or how they might be modeled in software? If some example might only take `Int` values, we would just consider that example to still take `Real` inputs?

**Comment by smiths** [comment]
I believe the answer to your question is yes.  We are interested in the "natural" type of the quantity.  If it is something that we count, then the type would be a natural number.  For instance, the number of slices in your ssp program is an integer.  There is no notion of half a slice.  The number of panes of glass in GlassBR ( @niazim3 ) is also a natural number.  If negative "counts" make sense, then we have an integer type.  An example doesn't immediately come to mind from our 5 projects, but I'm sure there is one in there.  If something is measured on a continuum, with negative and positive values, we have a real (R) value.  Many of the quantities in our 5 projects should have the type Real.

In the implementation natural numbers might be implemented using integers and reals might be implemented using floats or doubles, but in the  SRS we shouldn't be making these implementation decisions.

**Comment by njericha** [comment]
@hmadej defaulted everything to Real 68e328f705b872dfc3c2e0cf5c4a31bf5a5f55b8 and I've made my necessary changes 106257b0e07a1ede8e03de4666884e6112b364a4
