### ISSUE TITLE
GlassBR Code Review (issue #269)

### ISSUE THREAD

**Issue by hmadej** [JacquesCarette/literate-scientific-software#272]
issue #269 

- [x] s6_1_1_bullets looks like it could be done in a better way, pulled out separately and put back together.
- [x] s6_2_1_list eqnblock could be pulled out into individual parts, looks like this could be valuable information.
- [x] s6_2_5_table1, s6_2_5_table3 constraints could be written as expr and pulled out, also valuable information
- [x] s6_2_5_table2 looks like numbers could be written as expr and pulled out
- [x] s7_1_list should be broken apart into separate parts and put back together, it does too many things in one place?

### @njericha's additions 

- [x] Go through all files (specifically TMods.hs and IMods.hs) and update `(P $ thing ^. symbol)` to `getS thing`
- [x] Remove all instances of `:+:` in all files where possible. Example, line 63 in IMods.hs, you can use `sParen` rather than explicit brackets.
- [x] Use `UDiv` rather than `UProd` in Units.hs
- [x] Update equations to use `exp` to create an exponential rather than hard code an e^x. Example, line 25 DataDefs.hs (take a look at Expr.hs in Language)
- [ ] Fix `temporary` in Unitals.hs (bottom of the file) to use ConVar rather than VarChunk. This way you can build these chunks off of `non-factored load` defined in Concepts.hs. You may need to redefine `non-factored load` to be a ConceptChunk. This shouldn't break where it is used though.

**Comment by niazim3** [comment]
Updated changes to `s7_1_list` in commits dae3034...389668a.

**Comment by njericha** [comment]
- [ ] Go through all files (specifically TMods.hs and IMods.hs) and update `(P $ thing ^. symbol)` to `getS thing`

- [ ] Remove all instances of `:+:` in all files where possible. Example, line 63 in IMods.hs, you can use `sParen` rather than explicit brackets.

- [ ] Use `UDiv` rather than `UProd` in Units.hs

- [ ] Update equations to use `exp` to create an exponential rather than hard code an e^x. Example, line 25 DataDefs.hs (take a look at Expr.hs in Language)

- [ ] Fix `temporary` in Unitals.hs (bottom of the file) to use ConVar rather than VarChunk. This way you can build these chunks off of `non-factored load` defined in Concepts.hs. You may need to redefine `non-factored load` to be a ConceptChunk. This shouldn't break where it is used though.

**Comment by niazim3** [comment]
Replaced all `(P $ thing ^. symbol)` instances to `getS thing` instances as of commits 2b0f44d...cd7562c.

**Comment by niazim3** [comment]
Trying to use `exp` to create an exponential in **DataDefs.hs** like so 
![image](https://user-images.githubusercontent.com/28247301/27232519-5c3b260a-5284-11e7-9ff1-1d944e0c4571.png)
is giving me the following error:
![image](https://user-images.githubusercontent.com/28247301/27232525-632ee014-5284-11e7-9c7b-b058e40cb1ba.png)
What I don't understand is that when I sub in `log` for `exp` (since they are defined in the same manner), it works fine; are there any suggestions you have to approach this problem? @szymczdm @njericha

**Comment by niazim3** [comment]
**_Note to self_**: Need to incorporate `ar_max` into `s6_2_5_table2` (alterred as of commit beb1c93). Added a FIXME in the comments.

**Comment by JacquesCarette** [comment]
This is tricky, as I don't want to make a `Floating` instance for `Expr` (since it can represent other things too).

**Comment by niazim3** [comment]
@JacquesCarette
Clarification request: what is the last comment in relation to?

**Comment by njericha** [comment]
@JacquesCarette , That issue was fixed in db874fc09d37af0f4c2237f115bdcf0fbfa48fa2 by @szymczdm as mentioned here #272

**Comment by niazim3** [comment]
Closing this issue since the remaining change is directly related to issue #236.

**Comment by JacquesCarette** [comment]
The last comment was in relation to `exp` (and the error message seen above); one way to fix it would have been through adding some code to Drasil, but that was not a good solution.  The solution applied was better.

Seems there is only one bit left to do to close this one?
