### ISSUE TITLE
Create Greater-Than-or-Equal-to Sign

### ISSUE THREAD

**Issue by njericha** [JacquesCarette/literate-scientific-software#282]
Normally, having two measurements in physics "equal" to each other does not make sense because of measurement error. SSP, however, uses these frequently in Case expressions and also when referring to discrete quantities (such as slice i less-than-or-equal-to n).

**Comment by JacquesCarette** [comment]
So it is fair to compare integers for equality (even measurements), but not floats.  When you say 'discrete', what do you mean?

**Comment by smiths** [comment]
@njericha , I quickly went through the original SRS_SSP document and I did not see any instances where reals were compared for equality (x = y).  If you are aware of one, please create an issue for it, because you are correct that we want to avoid equality tests for reals.  As @JacquesCarette said, equality tests for integers is fine.  Using greater or equal to (>=) or less than or equal to (<=) is also fine with reals.

In my brief look over the document though, I did notice a mistake.  DD14 is ambiguous because there is both a test for <= and >=.  I will create a separate issue for this.  The cases are not disjoint.

**Comment by njericha** [comment]
@JacquesCarette Sorry for the confusion. I was referring to integers when I used 'discrete'. It is fair to compare equality for an integer number of things (number of apples in a basket) but not for something that can take a continuous range of values (the length of an apple). Since you could get many people with rulers to measure the same apple and get slightly difference measurements.

**Comment by njericha** [comment]
@smiths Thank you for clarifying. I suppose using (>=) for reals is ok to include a particular bound. And thank you for finding that issue. I will correct it when I get to implementing that expression.
