### ISSUE TITLE
Change quantity chunks to constraint chunks where necessary

### ISSUE THREAD

**Issue by palmerst** [JacquesCarette/literate-scientific-software#286]
I added constrained chunks to the language, so now you can embed constraints directly into the quantity chunks that have them.  I changed the plate_len chunk in the glassbr to a constrained chunk as an example (see commit 274aac2e0bc1da859d2385a81dda282562a3e005).

- [x] tiny
- [x] glassbr
- [x] gamephys
- [x] swhs
- [x] nopcm
- [x] ssp

**Comment by niazim3** [comment]
In **glassBR**, `standOffDist` has the following constraints: 
![image](https://user-images.githubusercontent.com/28247301/27343496-16e53336-55b1-11e7-8958-1a8d28221d3b.png), so it is completely dependent on the combinations of the inputs `sdx`, `sdy`, and `sdz` provided by the user, as seen in the following code from _CaseStudies\glass\Implementations\Python\Implementation\derivedValues.py_: 
   `# cal stand off distance
    temp = pow(params.sdvect[0], 2) + pow(params.sdvect[1], 2) + pow(params.sdvect[2], 2)
    params.sd = math.sqrt(temp)`... 
Should there be constraints placed on these as well? If so, any suggestions as to how that would work? @szymczdm @JacquesCarette @smiths 

For now, changes made to GlassBR associated with `standOffDist` are in cf65f11.

**Comment by niazim3** [comment]
Also, the following is currently under **Functional Requirements**:
![image](https://user-images.githubusercontent.com/28247301/27344166-672f2e62-55b3-11e7-8806-f51c3a4de6b7.png).
Since the program is asking the user to restrict their input `nominal thickness`, should that be considered a phyical AND software constraint(, even though it is not stated in **Data Constraints**)?

**Comment by palmerst** [comment]
@niazim3 Since SD is dependent on sdx, sdy and sdz,  the constraint on SD already indirectly constrains sdx, sdy, and sdz.  I think adding constraints there as well would be repeating information.

For the nominal thickness, I added boolean operators to Expr in 5ed57cdc98ec4e45cda2896fca55cff5b140472f.   You'll need them to express that constraint.  I believe that it would be a physical constraint because it arises from the fact that glass is manufactured in those nominal thicknesses.

**Comment by njericha** [comment]
@palmerst I cannot do this for SSP yet. The short reason is ConstrainedChunk is not an instance of Concept. 
SSP uses cqs wrapper to make the sspSymbols (for the Table of Symbols). SSP uses the definition (a trait only Concepts have) to make the Table. I cannot change the wrappers to qs since the table won't make correctly, I cannot use cqs since ConstrainedChunk is not a Concept, and I cannot not use a wrapper because I need a list of symbols to include UnitalChunks, ConVars, and ConstrainedChunk.

**Comment by palmerst** [comment]
@njericha cuc' now produces constrained chunks that are instances of Concept (3667f495c06d2502a77105535a64bb853d1d0e2f)

**Comment by niazim3** [comment]
Since `glass_type` is similar to `nom_thick` in that the input glass type must be an instance of a set (i.e. {AN, HS, FT}). Assuming that `glass_type` should be updated to a `ConstrainedChunk` type as well, it currently isn't possible to assign physical constraints to the constrained chunk `glass_type` due to the fact that "AN", "HS", and "FT" are abbreviations, and therefore, symbols cannot be extracted from `annealedGlass`, `heatSGlass`, or `fullyTGlass`.
I considered changing the abbreviations to symbols using (for example) Atomic "AN"`, but even then, the type would remain `CI` and that wouldn't solve the issue at hand.
Should the types be changed from `CI` (i.e. common idea) to something else like a `VarChunk`? Is changing the type the best solution?

**Comment by hmadej** [comment]
606388c covers the constraint for gamephys

**Comment by hmadej** [comment]
185f222 reduces duplication of information.

**Comment by AKM11** [comment]
SWHS, and by extension NoPCM, implement constraints as of commit 5ab5756dd5c6354dce7e3ab6587b896396d23d06.
