### ISSUE TITLE
Fetching only "Physical" and "Software" constraints?

### ISSUE THREAD

**Issue by niazim3** [JacquesCarette/literate-scientific-software#301]
I'm attempting to alter the functions created by @njericha (in commit c90c7e0) so that GlassBR can also use it to create its **Data Constraints** table; the changes necessary to do so include having 2 extra columns (i.e. **Software Constraints** and **Typical Uncertainty**). 
Currently, the following code produces the following output:
![image](https://user-images.githubusercontent.com/28247301/27401651-fdc87afc-5691-11e7-9fa9-4637dc1ae149.png)
![image](https://user-images.githubusercontent.com/28247301/27401403-216a3640-5691-11e7-9406-b40958a8f537.png)

The physical and software constraints are exactly the same because to my knowledge, `s ^. constraints` currently fetches all the constraints from `plate_len` (i.e. _a_):
![image](https://user-images.githubusercontent.com/28247301/27401560-a60285ec-5691-11e7-9822-bd890082fea8.png).
Would it be possible to create a lens that can be used to fetch only `physc` or `sfwrc` constraints from a `ConstrainedChunk` (to fix the duplication as well as update the `fmtConstr` functions to not be so similar)?

**Comment by szymczdm** [comment]
With the current implementation, phys and sfwr constraints have the same type (Constraint), but different constructors. Rather than mucking about with the lenses right now, I think it would be easiest if you just pattern match on the constructors(`Phys` and `Sfwr` respectively) by modifying the formatting functions to simply "skip" the constraints that don't belong in that section. Ex.

```
fmtConstrS s [Sfwr f] = E $ f (C s)
fmtConstrS _ [Phys _] = EmptyS
```

**Comment by niazim3** [comment]
Completed updates for this issue in commits a46a61d...f236ae7.
