### ISSUE TITLE
Added multiplication symbol when not needed

### ISSUE THREAD

**Issue by njericha** [JacquesCarette/literate-scientific-software#305]
Spotted a difference in the "interstice normal/shear relationship" and "resistive shear" theoretical models. One has multiplication done by showing the variables beside, and the other one uses a "*". In the original case study, there are no cases of `*` used for multiplication. This `*` shows up in Drasil generated files for some reason.
![capture](https://user-images.githubusercontent.com/26230851/27483658-6bfb3060-57f4-11e7-814e-5b1a9f729281.PNG)
![capture2](https://user-images.githubusercontent.com/26230851/27483662-6fd3afb4-57f4-11e7-9f91-9c3fbac19cb6.PNG)

**Comment by szymczdm** [comment]
This is actually a longstanding feature of Drasil for readability's sake. Since we don't currently have a proper way to add "prime" to a symbol (brought up in issue #265), any `Atomic` symbol that is more than one character should be separated using a `*`.

For an example where this is obvious, consider GlassBR's use of "LDF". If we multiplied LDF by any symbol starting with a capitalized english letter (ex. `F'`), we would end up seeing something like `LDFF'` which would be unclear as to whether it's a different quantity or a multiplication of existing quantities.

So it looks like adding "prime" decoration is key to resolving this current issue.

**Comment by szymczdm** [comment]
Try using`prime` instead of `Atomic "c'"` now. It should resolve this issue.

**Comment by njericha** [comment]
Looks good
