### ISSUE TITLE
Remove repetition of 'nominal thickness' definition in GlassBR

### ISSUE THREAD

**Issue by niazim3** [JacquesCarette/literate-scientific-software#309]
@JacquesCarette pointed out that there is repetition of information of nominal thickness, as `nom_thick` has the following as a definition (in **Unitals**): `nominal thickness t in {2.5, 2.7, 3.0, 4.0, 5.0, 6.0, 8.0, 10.0, 12.0, 16.0, 19.0, 22.0}`, and also has 
![image](https://user-images.githubusercontent.com/28247301/27541599-8368b4ba-5a52-11e7-83e6-16195779ee5d.png)
as the constraints.

@smiths Is it beneficial to have the description for `t` include the set from which the values should match the input? Can the definition simply be "nominal thickness" in the table of symbols since Data Definition 2 has the cases laid out as follows? 
![image](https://user-images.githubusercontent.com/28247301/27542010-f40dc6a0-5a53-11e7-8973-b8d73a1a30fb.png)

Note to self: also, in the **DataDefs** file, there is repetition of the same information:
![image](https://user-images.githubusercontent.com/28247301/27541665-bff25b3e-5a52-11e7-8a72-e089bd68001e.png)

**Comment by smiths** [comment]
@niazim3 , with respect to your question about not including the set of nominal thicknesses in the table of symbols, I would be okay with just saying nominal thickness.  However, I think there is something more significant at work here.  It actually shouldn't matter how many times the information is repeated in the generated document.  What matters is how many times the information is repeated in the "knowledge base."  You should be able to provide the information to Drasil once, and generate it as many times as you want.  Ideally, you would just pull this knowledge out an you could use it in the table of symbols, or the data definition, or wherever.

Rather than simply solving the problem by excluding the information in the generated document, maybe you can talk with @szymczdm for a way to capture the knowledge once and reuse it in any context that makes sense for it?

**Comment by niazim3** [comment]
@szymczdm Can there perhaps be some type of helper function that can look at the conditions of a case and produce a `Sentence` or `String` with all the values in a "{}" set? A function that does that may be helpful for glass types as well (
![image](https://user-images.githubusercontent.com/28247301/27704354-5f630e66-5cd8-11e7-90c4-fcf4c8be19f6.png)
).
(See commits 7e8ef50 and edaea0c.)

**Comment by JacquesCarette** [comment]
We should never need a `String` here.  It feels like the `String` in the `nounPhraseSP` is a mistake.  A noun phrase really should be reserved for "meaningful" phrases, not arbitrary descriptions.

**Comment by niazim3** [comment]
Update:
Created `displayConstrntAsSet` function that produces an output as follows 
![image](https://user-images.githubusercontent.com/28247301/28179750-ec95bea2-67d0-11e7-90c8-feca0ebfe62e.png); needs improvement (i.e. `or`s need to be `,`s and `t = ` shouldn't be repeated = for every possibility).
@szymczdm Is this going in the right direction?

**Comment by hmadej** [comment]
or is a logical operation, what this is saying is (t = 3.0) or (t = 4.0), t = (3.0 or 4.0 or ...) doesn't make logical sense.

**Comment by niazim3** [comment]
Yes, this function should be improved so that **nominal thickness t in {2.5, 2.7, 3.0, 4.0, 5.0, 6.0, 8.0, 10.0, 12.0, 16.0, 19.0, 22.0}** can be output; however, I don't think there is currently a way to extract the #s from the `t := (V "#")...` constraints.

**Comment by niazim3** [comment]
Changes can be viewed in commits 6e95430...72670d7.
