### ISSUE TITLE
Assumptions subsection for GlassBR

### ISSUE THREAD

**Issue by niazim3** [JacquesCarette/literate-scientific-software#314]
GlassBR's assumption 4 is as follows in the original document:
![image](https://user-images.githubusercontent.com/28247301/27590909-2b2546f2-5b1e-11e7-9d35-c0c23f2fdef1.png)
and after extracting the assumptions and implementing `enumSimple 1` on the whole list of assumptions (instead of the previous `enumSimple 1`, list of constants for A4, `enumSimple 5`), the assumptions are following is currently produced: ![image](https://user-images.githubusercontent.com/28247301/27560685-1e16d5c4-5a93-11e7-8db3-5e821260a2e2.png).
That is, each constant has it's own **A** label.
Is it reasonable to have the standard values as their own assumptions?
@smiths

**Comment by smiths** [comment]
@niazim3, Thank you for bringing this issue up.  I've given it some thought, and I don't think I like either option.  😄  I think the way the assumptions were originally written in the "manually" produced version wasn't the best approach.  I think we should make use of one of the unused sections from the original requirements template -- the Section "Value of Auxiliary Constants."  You can find the paper here, if you are interested:

https://gitlab.cas.mcmaster.ca/SEforSC/se4sc/blob/git-svn/SciCompAndSoftEngPapers/SmithAndLai_2005.pdf

I would rather have this section back in the template, and then put the constant values there.  I think that would make it easier for @palmerst to access the values for the generated code.

If you create a new table for constants, I would still keep an assumption that points to the table.  This will give you traceability information so that someone can track down the values of the constants.  I suggest the "new" assumption would be something like:

A4. The values provided in Table ? are assumed for the duration of load (td) and the material properties of E, m and k.

From my understanding of the implementation of Drasil, it wouldn't be difficult to add another section and table, but @szymczdm can advise us if this is a more significant request than it at first appears.

**Comment by szymczdm** [comment]
It should be fairly straightforward to add the new section and table. If anything, it may just take a bit of time.

**Comment by smiths** [comment]
Sounds good.  Thank you @szymczdm .

**Comment by niazim3** [comment]
This issue closes as of commit a1e336f. **Assumption 4** and the new section are produced as follows.
![image](https://user-images.githubusercontent.com/28247301/27606457-63209cde-5b4e-11e7-825e-ec37daa582da.png)
![image](https://user-images.githubusercontent.com/28247301/27606485-88b8a31a-5b4e-11e7-8795-12f9dbfdf7e5.png)
The new section is placed near the end of the document (i.e. right before **References** as seen in the linked gitlab document).
Please do let me know if some enhancements in the output/code is necessary.
