### ISSUE TITLE
Ambiguous Use of Tau in SSP

### ISSUE THREAD

**Issue by njericha** [JacquesCarette/literate-scientific-software#318]
I'm not sure if tau means "shear stress acting on the base of a slice" or "mobile shear on a slice". Also, tau is not defined in the table of symbols so I would need to know what the correct term and definition should be to create the Chunk. Finally, tau_i is used in the equation but tau without i is used in the sentences.
![2017-06-27](https://user-images.githubusercontent.com/26230851/27605475-d7d52ed6-5b4a-11e7-9368-aabc0b656363.png)

**Comment by smiths** [comment]
We don't need the word mobile.  You can remove that and just go with "shear stress."  As far as the subscript goes, if the shear stress is for a slice, it should have a subscript i.  The original documentation is incorrect in this case.

@szymczdm and @palmerst ,  you should remember this example when you are motivating your research.  The process of refactoring the documentation has revealed some subtle errors and omissions.  I think this is related to the process of de-embedding knowledge, since the natural goal is to de-embed a minimal amount of information and then correctly reuse/transform it.
