### ISSUE TITLE
Necessity of "Specification Parameter Values" Table in GlassBR?

### ISSUE THREAD

**Issue by niazim3** [JacquesCarette/literate-scientific-software#322]
@smiths 
![image](https://user-images.githubusercontent.com/28247301/27643435-119b534e-5bef-11e7-8223-cf6422a5dde1.png)

How significant is the Table 3 above? SWHS, GlassBR, and NoPCM all have it under the subsection of **Data Constraints**, however, SSP and GamePhysics don't have it at all (i.e. they only have a table for **Input Variables** and a table for **Output Variables**).
The `max` and `min` bounds are used only in the software constraints section, which brings the question of whether or not we can directly insert the values of these bounds into the software constraints so that we can remove this third table that is causing an inconsistency between the examples?

**Comment by smiths** [comment]
Great question @niazim3 .  This table should be in all of the examples.  We definitely do not just want to replace the symbolic constants in the constraints table with their values.  Just like in coding, we use symbolic constants to improve maintainability, and understandability.  If someone wants to change the values of a symbolic constant, they just have to change it in the table.

However, I agree with you that there should not be a table for Specification Parameter Values.  Instead all of this information should go in the Auxiliary Constants Table mentioned in Issue #320.

Can you please create an issue for all of the projects to add the Auxiliary Constants Table?  Every example should at least have min and max constraints that would go in this table.

**Comment by njericha** [comment]
This makes some sense for generating the code since all the values that bound variables are in one table. In terms of readability of the document, it feels weird to have the constraint values show up in Auxiliary Constants Table. When reading the Data Constraints Table, all you could see for physical constraints is `x_min <= x <= x_max`. You would then have to view a different section to see what those values are.

As a related issue, how can we express that are confined only by their space ex. 0<theta<90 or length>0? Would we use the Auxiliary Constants Table or remove the constraint and instead display the space ex. length element of R+? If we keep these as constraints then we have duplicate information ex. length>0 as a constraint and length has a space of R+.

**Comment by smiths** [comment]
@njericha , I can see what motivates your comment that the auxiliary constants are far from the table where they are used, but I don't see this as a problem.  The names of the constants tell the reader what they are.  From your example, you can see that the value of x is bounded.  That is usually the part that will be of interest.  The validity of the specific values can be checked separately.  This arrangement gives us a reasonable example of the design principle of separation of concerns.  In a programming language it isn't uncommon for the value of a constant and the use of the constant to be separated by many lines of code.  This doesn't tend to be a problem.

As far as spaces go, if there is a space that expresses the constraints, then you don't need the constraint in the table.
