### ISSUE TITLE
Incorrect referencing from Requirements section

### ISSUE THREAD

**Issue by niazim3** [JacquesCarette/literate-scientific-software#323]
In the attempt at removing the instance of `enumSimple 5`, I'm in the process of pulling out the contents so that `enumSimple 1` can be applied to all the requirements.
In order to change the type of `s7_1_req1` from `Contents` (which includes its corresponding table as follows 
![image](https://user-images.githubusercontent.com/28247301/27644442-94c4ab38-5bf1-11e7-8c17-982a95f76698.png))
to `Sentence` that refers the user to where the table is (for now at the end of the list of requirements: 
![image](https://user-images.githubusercontent.com/28247301/27644509-c24f92ac-5bf1-11e7-92cb-983f8416fcad.png)).

Unfortunately, when the `this Table` link is clicked from **R1**, the user is actually taken to the **Table of Symbols** at the beginning of the page.
I have referenced this issue from the commit where the I started the modification of the Requirements section.

**Comment by szymczdm** [comment]
This error in referencing is occurring because you're using the Table Of Symbols `table` function to create the table. It automatically assigns the reference label "TableOfSymb" (or something like that), which then references the first table of symbols.

You need to create the table using a different function / the raw `Table` constructor.

**Comment by niazim3** [comment]
Issue closes as of commit 31cd381.
