### ISSUE TITLE
"No instance for (Concept ConstrainedChunk)" error

### ISSUE THREAD

**Issue by niazim3** [JacquesCarette/literate-scientific-software#334]
Since GlassBR has `ConstrainedChunk`s being built off of `VarChunk`s (using `cvc` constructor defined in **Constrained.hs**), I believe a new `UncertQ` constructor is needed (since there is no definition or units (unlike the `UnitalChunk` type)). Started to define a new constructor in the following ways:
![image](https://user-images.githubusercontent.com/28247301/27739069-60ebecd2-5d7b-11e7-9aef-4139a3ede76c.png)
and received the following error:
![image](https://user-images.githubusercontent.com/28247301/27739082-68dc74e8-5d7b-11e7-9312-2beb766511c8.png).
Trying to build an `UncertQ` using `uq` and passing in a  `ConstrainedChunk` as follows 
![image](https://user-images.githubusercontent.com/28247301/27739315-2718b23c-5d7c-11e7-8077-f27cbfff7286.png) 
also led to the same error (
![image](https://user-images.githubusercontent.com/28247301/27739357-4a0286e2-5d7c-11e7-9cf7-e536a6193678.png)). 
How should I be approaching an error of this nature? Also, why would this error pop up if it holds less data than a `UnitalChunk`?

**Comment by szymczdm** [comment]
It looks like there's a "Concept" constraint being forced somewhere that may not be absolutely necessary (or it's necessary and there's no instance of it in the chunk(s) you're using). 

I believe @njericha is the last one to have modified Uncertain Quantities, so it might be worthwhile for the two of you to take a look and discuss it. If you can't figure it out in a timely manner, just let me know and I'll jump in to have a look around.

**Comment by niazim3** [comment]
I was able to fix the above error by removing all instances of "Concept" being implemented in UncertaintyChunks.
Although, this has affected SSP quite significantly as the **Table of Symbols** is no longer being fully generated (I've changed the type creating the `SystemInformation` in the body `[QSWrapper]` from originally being `[CQSWrapper]`).
I'm currently looking into why the same arguments being passed into `SI` as GlassBR isn't producing the **Table of Symbols** in SWHS and SSP.

**Comment by szymczdm** [comment]
If you had to make such a sweeping change, it was probably not the right move. Likely those examples use `defn` instead of `term` in the table generation, which means the `Concept` part is absolutely necessary. It seems like we'll need a new data type for uncertain quantities that aren't concepts, and a function that will utilize them (unless I'm missing something, which could be the case as I haven't had a moment to look deeper into what's causing this issue).

**Comment by niazim3** [comment]
In that case, I won't push my changes yet. Thanks for the input @szymczdm, I'll be looking through the **Constrained.hs** file to create a new data type.

**Comment by niazim3** [comment]
Issue closes as of commits f94a26e...3824a97.

**Comment by njericha** [comment]
@szymczdm when #227 was fixed, SSP used the definition part of Unitals/ConVars to create the table of symbols. For this reason, SSP must use `cqs` wrapper on all of the sspSymbols (so the definitions can be accessed). This is not the case for the other examples since this definition grabbing is not done. Only the term is being stated in the table of symbols for these examples.
