### ISSUE TITLE
Tables with many columns extend past margin

### ISSUE THREAD

**Issue by bmaclach** [JacquesCarette/literate-scientific-software#34]
Tables with enough columns will extend past the right margin, as shown below:

![drasiltableextends](https://cloud.githubusercontent.com/assets/18634568/15747978/097bbec4-28ab-11e6-943d-7ac2ec157308.png)

It looks to me as if there is enough spacing between the columns that this table could fit within the margins if that spacing were reduced. Even if that's not the case, should the column headers wrap around to multiple lines so that the table can fit within the margins?

This problem only exists for the SRS Doctype, not the HTML files.

**Comment by JacquesCarette** [comment]
Unlike the previous issue, this one is incredibly hard to address.  Even LaTeX itself does not address this.  You need to know a huge amount of information (page size, font size, etc, etc) to be able to calculate this, none of which are available to Drasil.

I have assigned this one to Spencer, because this is really about the design of the SRS template itself, not about lower-level features of Drasil.

**Comment by smiths** [comment]
Since the time of this issue being posted we have had success with generating graphical representations of the graphs that show this traceability information.  If a table does not fit, then we could include the generated graph.  We also could create tables that are a subset of the full table.  For instance we could generate multiple tables each with a subset of the rows from the full table.  That is, we could have a table that shows the traceability between assumptions, a table for the theories and a table for the data definitions.

I am going to close this issue at this time.  We can reopen it if and when the appearance of the tables in our examples again becomes a problem.
