### ISSUE TITLE
De-embed GlassBR

### ISSUE THREAD

**Issue by szymczdm** [JacquesCarette/literate-scientific-software#342]
Here's a list of places where knowledge is still embedded and needs to be pulled out (see #339 for more information) in Body.hs, I've made explicit mention on several as a starting point, but there are likely more places with embedded knowledge:

- [x] startIntro (`glaSlab`, `blastRisk`, etc. all captured, but still embedded)
- [x] s2_1_intro_p1 (`gLassBR`, `document`, etc. still embedded)
- [x] s4_1_bullets (`endUser`, etc.)
- [x] s5_2_bt_sent1
- [x] s5_2_bt_sent2
- [x] s6_1_2_list_physys2
... etc.

Some of this may even need new knowledge capture or changes to odd conventions, as certain things will jump out. Either way, this knowledge will still need to be de-embedded.

**Comment by niazim3** [comment]
@szymczdm 
Would it be possible to get some clarification on how instances like `glaSlab` and `blastRisk` could be de-embedded from the `startIntro` `Sentence`?
![image](https://user-images.githubusercontent.com/28247301/27873357-d5b04732-6179-11e7-9276-fc349ac15fab.png)
Are we supposed to interweave the chunks used in the sentences with a list of sentences (so that there is a [`Sentence`] and [`Chunk`]), where the list of chunks would be pulled to the "knowledge" section of the code?

**Comment by szymczdm** [comment]
In some instances it will mean parameterizing the `Sentence`, others will mean creating new combinators, etc. You can see @hmadej and @JacquesCarette's conversation on #344 for some more information.
