### ISSUE TITLE
SSP Symbol Inconsistency

### ISSUE THREAD

**Issue by njericha** [JacquesCarette/literate-scientific-software#348]
### The case study SRS for SSP starts by defining S_i and P_i as follows.
![2017-07-07 4](https://user-images.githubusercontent.com/26230851/27963505-4c8f834c-6303-11e7-81df-9eafbfc2504f.png)
![2017-07-07 2](https://user-images.githubusercontent.com/26230851/27963545-6abb9306-6303-11e7-8628-1969eafaa3f3.png)
![2017-07-07 3](https://user-images.githubusercontent.com/26230851/27963550-6df23eee-6303-11e7-941c-0ce6ad595dd7.png)

### But later, the meaning is flipped, and P_i is replaced by tau_i. tau_i isn't mentioned in the Table of Symbols.
![2017-07-07](https://user-images.githubusercontent.com/26230851/27963597-916adf16-6303-11e7-8a0f-d1298c13e013.png)
![2017-07-07 1](https://user-images.githubusercontent.com/26230851/27963605-93b7bc8a-6303-11e7-85df-1f2436769d9e.png)

I am unsure what symbol should be used here.

**Comment by szymczdm** [comment]
Wow, that's a pretty big inconsistency, nice find! @smiths should be able to point you in the right direction.

**Comment by smiths** [comment]
@njericha , I believe the difference comes about from confusion between shear force and shear stress.  Tau is a shear stress, with units of N/m^2.  S_i and P_i are defined as forces, with units of N.  To figure out where we need to make the corrections, please look at the original source material and check the units of the equations.

**Comment by njericha** [comment]
tau must have units N because FS has unit 1 (since it is a ratio)

**Comment by smiths** [comment]
If tau must have units of N, then there is a mistake in the equation.  tau is a shear stress, and shear stress has units of Pa (N/m^2).  It looks like this inconsistency is in different places in the case study.  I looked at T3 (in the original "manual" document) and the use of P here is incorrect.  P should be tau.  You can see this from the Wikipedia page on Mohr Coulomb Shear Strength:

https://en.wikipedia.org/wiki/Mohr%E2%80%93Coulomb_theory

The units for this question do not work.  P seems to have units of N (based on the definition of P_i), but the RHS of the equation has units of Pa.

As we have discussed before, the SSP example was not reviewed as thoroughly as the other documents.  I think some of the derivations have confused shear stress with shear force.  Can you please go through the equations @njericha and verify the units?  Please also add the symbol for tau, where tau is shear stress, with units of Pa.  (tau = F/A, where F is the shear force and A is the cross-sectional area.)  Please also correct T3.  Propagating this fix might address some of the other problems in the document?

Rather than read the SSP document as a Drasil coder, please read it from a physics perspective.  It should agree with the equations from ZhuEtAl2005.

**Comment by njericha** [comment]
@niazim3 and I are looking at this issue and noticed this switch in T1 would imply G3 should also be tau (not P)? Another issue comes up with c' in GD3, it has units Pa but in this equation, it would need units N/m^3 since b_i has units m. If we don't change P_i, then c' would need units N/m.

**Comment by njericha** [comment]
But T3 (with tau replacing P_i) would suggest c' should have units Pa

**Comment by smiths** [comment]
No, for GD3, it actually appears correct to me.  It should be P, not tau.  It is confusing though, because the derivation is not explained.  The derivation starts with T1, then both sides of the equation are multiplied by b_i*sec(alpha)*1.  This is the kind of step that can be frustrating to understand.  It is actually one of the reasons why I think we need to go to the trouble of documenting our equations.  😄 The original is not well documented on this point.

b_i*sec(alpha)*1 actually has units of m^2.  The extra 1 at the end is to represent a unit of width into the page.  The slope stability problem is made into a 2d problem by assuming that the depth into the page is infinite.  Therefore we just talk about one unit of width into the page.  Once you multiply by b_i*sec(alpha)*1, you convert the shear stress into a shear force (P) and the effective normal stress (sigma') into an effective normal force (N'_i).  The units then for every term in the equation are newtons (N).  

@njericha , could you please fix the description of GD3 to clarify how T1 is used, along with the geometry of the problem, to come up with the resistive shear force?  Could you also please change the title of GD3 to resistive shear force?  The original use of the term shear alone is ambiguous, since we don't know if it is a shear force or a shear stress.

**Comment by smiths** [comment]
Yes, c should have units of Pa (http://www.geotechnicalinfo.com/cohesion.html).

**Comment by njericha** [comment]
Thank you, that makes a LOT more sense 😄

**Comment by smiths** [comment]
Thank you @njericha .  I really appreciate you bringing up issues like this.  As I've said before, I don't have as much confidence in the ssp example.  The more we work through issues, the more my confidence will build.  😄

**Comment by njericha** [comment]
GD3 now reads;
The Mohr-Coulomb resistive shear strength of a slice τ_i from T3 is multiplied by the area b_isec(αi)*1 to obtain the resistive shear force P_i. Note the extra 1 is to represent a unit of width which is multiplied by the total base length of a slice ℓ_b,i of the plane where the normal occurs, where ℓ_b,i=b_isec(αi) and b_i is the x width of the base. This accounts for the effective normal N'_i=N_i-U_b,i of a soil from T4 where σb_isec(αi)*1=N'_i.

**Comment by smiths** [comment]
Hello @njericha.  Can you also please clarify that the normal stress is multiplied by the area to get the normal force?

**Comment by njericha** [comment]
f4cac4c is actually for `#319`

**Comment by njericha** [comment]
@smiths After more reading and trying to fix the errors, it seams like the issue with the factor of safety equation above (equation 30) starts with equation 26. sigma has units pascal but so does the normal stiffness K_bn,i. I think this sigma is used to represent a Force over a length rather than an area since this length gets multiplied in equation 31. This correction with sigma would also make equation 28 consistent and thus close this issue.

This means S_i and tau_i are un-normalized stresses of units N/m in equations 26-31. c must also be N/m here to match. Should I create new symbols for these three quantities since they are neither forces (N) nor typical stresses (Pa)? And which symbols should I use?

**Comment by smiths** [comment]
@njericha , my thinking is to change the units of the stiffness term, not those of the stress or cohesion.  Stress and cohesion are standard physical concepts, where the stiffness is a derived idea that takes advantage of something like Hooke's law, but doesn't actually follow it.  If you derive the units of K in Equation 26 from the units of sigma and delta v_i, the units are Pa/m.  These units agree with the units for Equation 28.

I haven't traced all of the changes through the derivations.  Would giving K units of Pa/m solve the inconsistencies?

**Comment by njericha** [comment]
Unfortunately it would not solve equation 31 since it multiplies by an additional length. It feels like K should be (Pa) since DD13 multiplies K by L and delta

**Comment by smiths** [comment]
Equation 31 is fine with K having units of Pa/m.  The top and bottom of the equation are multiplied by l, so the change in units is the same for the top and bottom of the equation.  Multiplying Si and tau_i by l returns something with units of N/m.  This is the force per unit width into the "page."  This is also how you would interpret DD13.  The units for K are Pa/m, multiplying this by m^2 returns units of N/m.  For one unit of width into the page, the force is in Newtons.

**Comment by njericha** [comment]
I think this closes the issue. Took a while to go through and trace all the symbols. The hard part was remembering the implied "length of 1 m into the page" in equations.
