### ISSUE TITLE
SSP Constants are not mentioned as inputs

### ISSUE THREAD

**Issue by njericha** [JacquesCarette/literate-scientific-software#353]
In data definition 14 of the case study, there are constants that are used in a calculation which are inputs to this formula. "&kappa;" and "A" are not in the table of symbols or in the input data tables. From a code generation perspective, should these be predetermined constants or added to the list of inputs?

![2017-07-19](https://user-images.githubusercontent.com/26230851/28372111-d37004c8-6c6c-11e7-8371-ff28a18944cb.png)

**Comment by smiths** [comment]
Hello @njericha .  Please add the symbols to the list of inputs.  They are mentioned in the StolleAndGuo2008 paper.  The values might be changed, so we don't want them to be constant.

**Comment by smiths** [comment]
For now, you'll just have to call them constants, since I am not aware of any name for them.  Additional information, like units and typical values are in StolleAndGuo2008.  The information in StolleAndGuo seems to be incomplete.  Do your best on this.  If you are not sure, you can put a question mark in the description.

I do not want us to put too much effort into the stiffness part of the case study.  To be honest, I do not have an abundance of confidence in this part of the document.  The Morgenstern-Price part seems better put together to me.
