### ISSUE TITLE
Remove unit conversions from equations?

### ISSUE THREAD

**Issue by smiths** [JacquesCarette/literate-scientific-software#358]
After recently looking at Beason et al (1998), I was surprised to see that the equations from the ASTM do not include explicit unit conversions.  I had thought the conversions (/1000 etc) were from the original source material, but now it appears that the student that originally wrote the SRS documentation put the conversions in herself.

@JacquesCarette  and @niazim3 , would you be okay with changing our equations to remove these conversions?  As a consequence, we will also need to make sure that all of the inputs are in standard SI units.  In particular, the dimensions a and b would then be in m, not mm.  Young's modulus would  also need to be changed from kPa to Pa.  If we still want the user to enter the dimensions in mm, we can have a requirement that takes the input in mm and promptly converts it to m. 

I would be surprised if you didn't agree that the equations without unit conversion look nicer, but I thought we should discuss this issue, because maybe making this change at this time will be counterproductive.  I would be fine with waiting until later to make the modification.

**Comment by niazim3** [comment]
I personally don't have a preference, however, I do agree that the equations would look cleaner if the conversions were removed. That being said, the **h** value (i.e. the actual thickness) 
![image](https://user-images.githubusercontent.com/28247301/28466553-d4efefae-6dfa-11e7-845f-660a3920bce4.png) would also have to be input as m instead of mm, correct? Changing **h**'s units would result in the data definition for **h** to not look so nice; (i.e. 11.91 mm => 0.01191 m).
![image](https://user-images.githubusercontent.com/28247301/28466671-269c8600-6dfb-11e7-9ef6-0aaaa16cc1c2.png)...
Would it make sense to have the user input the values in mm, and some data defs use the mm value while the others use the converted m value? I'm not sure how effective this would be though, since this may cause confusion for the document's readers...

**Comment by smiths** [comment]
Good point @niazim3.  However, since t is just a label, not an actual value, we can use mm for t without any inconsistency.  The conversion of t to h would not be seen by the users.  As long as the SRS document readers remember that t is the "name" or "designation" of the glass thickness, I do not think confusion would be a problem.

**Comment by JacquesCarette** [comment]
I agree.

And for defining `h`, we could have `h` defined as that above piecewise divided by 1000 (to adjust the units).  That would keep both the label and value readable.

**Comment by smiths** [comment]
Great idea Jacques.  @niazim3, can you please make this change in units to h, and use @JacquesCarette's idea of separating out the divide by 1000.  To keep the audit trail straight, could you please create a new issue for this task?

**Comment by niazim3** [comment]
Implementation of discussed solution will be done in issue #363.
