### ISSUE TITLE
Additional subscripts for defined constants/variables in text/equations

### ISSUE THREAD

**Issue by palmerst** [JacquesCarette/literate-scientific-software#36]
I require a way of adding subscripts to the symbols of my defined constants/variables in some circumstances.

For example, a constant/variable is defined with symbol T, but I need to write the equation x = T_i  -  T_(i-1). Sometimes these are already subscripted,  i.e. symbol T_w needs to become T_(w,i).

**Comment by szymczdm** [comment]
Can you give a bit more detail on this? We need to know (conceptually) exactly what these subscripts are representing.

**Comment by palmerst** [comment]
For my case, the problem is broken down into slices.  A lot of equations contain subscripted versions of defined symbols to denote values for a particular slice number (or sometimes interslice boundary number).  See attached image.

![sub_example](https://cloud.githubusercontent.com/assets/14371273/15917970/b849b608-2dcf-11e6-8113-421223bdee9c.png)

**Comment by JacquesCarette** [comment]
So what T turns out to be is a function from 'interfaces' to a force (that last bit could be wrong, but that's not relevant).  We happen to not use T(i) as the notation, as the interface number is considered different than an 'input', so it's a subscript.  So that means that the meaning (a function) and the display (subscript) are not inter-derivable from each other.  We need a design to handle that.

I would like to see an example of double subscript.  I wonder if that's good notation.  [It could be].

**Comment by palmerst** [comment]
Example of double subscript:

![double](https://cloud.githubusercontent.com/assets/14371273/15942727/a36319f8-2e53-11e6-8f9d-261429bb4bdb.png)

**Comment by JacquesCarette** [comment]
Very tricky indeed.  This will be difficult.  Right now, we might have to settle for ${y^{wt}}_{i}$.  That should be implementable shortly.  But otherwise it is going to need a more extensive "programmable rendering" language than we have now.  That's probably lower priority.

**Comment by njericha** [comment]
Double subscripts can be done and indexing is being looked at in #265
