### ISSUE TITLE
Implement Suggestions from Issue #358 (Unit Conversions for GlassBR)

### ISSUE THREAD

**Issue by niazim3** [JacquesCarette/literate-scientific-software#363]
This issue stems from #358.

- change units for **h**, **a**, **b**, and **E**
- update DD2 to separate out the divide by 1000

**Comment by niazim3** [comment]
Completed as of commit 3af3bbf.
Outputs are now as follows:
DD9-> 
![image](https://user-images.githubusercontent.com/28247301/28529206-f77ce436-705d-11e7-9f35-4c42d8bd058f.png)
DD1->
![image](https://user-images.githubusercontent.com/28247301/28529259-112e72aa-705e-11e7-9ebf-9339bb1c29bf.png)
Changes made to DD2 cause the output to have double `=`s 
![image](https://user-images.githubusercontent.com/28247301/28529308-37e0736c-705e-11e7-90be-4c0067874317.png).
Since Data Definitions are being generated automatically, I'm not sure how to remove the first `h = ` from the piecewise function... perhaps a separate issue needs to be created for this?

**Comment by smiths** [comment]
Looks good @niazim3 .  However, DD2 should not be h/1000, but 1000*h.  I'm also not sure how to remove the leading h = for DD2.  I'm not sure if this is what @JacquesCarette, had in mind.  I was thinking he meant to divide the value of h by 1000 after it was assigned, but I'm not sure how we get across the idea of sequence in our Drasil tool.  A fallback position is to simply divide each number by 1000 in the piecewise function definition.  It wouldn't be that bad, since these numbers only show up here, as far as I recall.

**Comment by niazim3** [comment]
Output is now as follows:
![image](https://user-images.githubusercontent.com/28247301/28531187-0b9bbcf2-7064-11e7-8f57-58c7173dbe0e.png)

**Comment by smiths** [comment]
What about just writing 0.00216, 0.00259 etc?  I think that might look nicer than all of the divide by 1000s explicitly in the equation.

**Comment by niazim3** [comment]
That's true, the operation is repetitive...

**Comment by niazim3** [comment]
Note to self:
Dividing the actual values by 1000 lead to the following: 
![image](https://user-images.githubusercontent.com/28247301/28531850-04fe4b1a-7066-11e7-82a4-a159e09635d6.png).
Need to use a function that rounds to a certain number of decimal places...

**Comment by JacquesCarette** [comment]
What I meant was `h = 1/1000 * Case(...) `.

**Comment by niazim3** [comment]
![image](https://user-images.githubusercontent.com/28247301/28539959-8879cde6-7081-11e7-952c-37a93f7d2299.png)
Issue closes as of commit .

**Comment by JacquesCarette** [comment]
Excellent.
