### ISSUE TITLE
Input Bibliography Citations

### ISSUE THREAD

**Issue by njericha** [JacquesCarette/literate-scientific-software#370]
Citations for Bibliographies is in a working state as of ff2ab371700865704109ce39d9c455d93b6b89bb. Currently, you can cite books and journal articles. See 63fc2f78b0032f00cbd2f36c4bb97eb5afa37392 for an example on how to do this. If there are other things that need citing or issues that come up, comment here.

- [x] SSP
- [x] GamePhys
- [x] GlassBR
- [x] NoPCM
- [x] SWHS

**Comment by danscime** [comment]
Not sure if you are aware, if the last author has a n initial for a middle name, there is a double period

**Comment by danscime** [comment]
Also SHWS and SSP share a reference, should we be connecting the two? I feel like Drasil would have a library database of scientific documents and references

**Comment by JacquesCarette** [comment]
@danscime absolutely.  In the same way we have 'global' databases for a lot of things, we should absolutely have a global one for reference material.

Note that, like Concept and Quantity, it can still be organized into sub-databases.

**Comment by danscime** [comment]
SWHS has a reference that says "Personal Notes"
Is that proper for a citation? (What should be done?

<img width="526" alt="screen shot 2017-08-03 at 11 04 21 am" src="https://user-images.githubusercontent.com/28261339/28928610-a426717c-783b-11e7-8558-d7acc7e1370c.png">

**Comment by JacquesCarette** [comment]
It is a 'proper' citation in that it properly attributes the work to the person who created it, even though that work may not have gotten published.  So what needs done is that a Misc type of citation needs to be added to the backed (which is also what bibtex does).

**Comment by danscime** [comment]
Need to add "Editor" Field

**Comment by njericha** [comment]
0d45ba45c4433ed3349c45215701ec031f9b036d Added Misc and Online

**Comment by njericha** [comment]
Added editor field^

**Comment by niazim3** [comment]
GlassBR has multiple sources that are standards issued by ASTM (American Society for Testing and Materials). 
![image](https://user-images.githubusercontent.com/28247301/28974753-6e83eca0-7905-11e7-83c6-d843411a2dae.png)
According to _https://www.astm.org/Msgs/citing.htm_, the first field is supposed to be filled in with the name of the standard issuing body, which can be seen as the equivalent to `Author` in Drasil's rendering...
An issue pops up since the name of the `Author`s in these cases has spaces, and using the `mononym` constructor as a temporary hack led to Tex being unable to make a label for these citations:
![image](https://user-images.githubusercontent.com/28247301/29081869-ce866252-7c31-11e7-908c-2f1e102d02db.png)
![image](https://user-images.githubusercontent.com/28247301/29080899-1036fb74-7c2f-11e7-909e-1d2534aad576.png).
Should a new constructor be created for standard issuing bodies?
Should the `cite` function from TeX\Print.hs be alterred so that the spaces present in a name be replaced with **_**s?

**Comment by njericha** [comment]
I can add `_` to replace spaces when using `mononym` in TeX.

**Comment by njericha** [comment]
This committee _is_ the `Author` so it makes sense to use that type constructor, the only thing that could be added is the idea of a `Group` of `People` which we could designate a name.

**Comment by njericha** [comment]
657623e Adds underscores

**Comment by niazim3** [comment]
GlassBR is mostly updated for this issue, however, the remaining needs to be fixed:

- [ ] "L. Beason..." source shouldn't come before "ASTM ..." in LaTeX (proper alphabetization?)
- [ ]  Proper categorization of "Standard E1300-09a" and "Book of standards 15.02" for referencing standards
- [ ] _Place_ from the Koothoor citation should be displayed in TeX?
- [ ] Name implementation for authors with special characters in their names  (e.g. Ralyt**é**)  (Separate issue?)

**Comment by njericha** [comment]
I found this note in regards to _Place_
>*Only include the city of publication if the book was printed prior to 1900, has versions that differ in one country than another, or if it is a rare book.
http://www.easybib.com/guides/citation-guides/mla-8/cite-book-mla-8/
APA however does use the place in a citation.
