### ISSUE TITLE
Move CaseStudies out from Drasil repo?

### ISSUE THREAD

**Issue by JacquesCarette** [JacquesCarette/literate-scientific-software#415]
They have a weird side effect: because there is so many files, it makes it look like this repo is more C than anything else! I would like Drasil to be classified as a Haskell project.

@szymczdm @smiths @palmerst I would like your opinion. I can do the deed if we decide to go forward.

[Note that we can use git submodules to have our local mirrors still have the CaseStudies in the same spot]

**Comment by palmerst** [comment]
I think it's a good idea.

We also have a copy of the chipmunk source code in the repo for some reason under Chipmunk2D-master which is adding a lot of C code:  https://github.com/JacquesCarette/literate-scientific-software/tree/master/Chipmunk2D-master  -- I'm not sure why this is in the repo?

**Comment by smiths** [comment]
I can see the value of moving the case studies out of the Drasil repo, but it is worthwhile to consider why they were originally moved into the Drasil repo.  Originally, the case studies were separate (in a misnamed repo called drasil, no less).  We moved them over because the summer students were getting confused, and because we were making some changes to the case studies and to the drasil code.  It just made sense to have everything together.

Having said that, the SWHS repo has always been separate.  I've cited it as an example in papers, so I want to maintain the GitHub version.  We don't want to introduce the maintenance nightmare of having the example in two places, so the Drasil repo just points to the SWHS repo in the case studies folder.

It seems like adding submodules in git would be a similar step to pointing to the external repos, but it would take things further.  I did a very quick search on working with submodules, and I'm not sure I'm encouraged by what I read:

https://github.com/blog/2104-working-with-submodules

There are some warnings in this article that implies that submodules might be more work than they are worth.

Rather than submodules, maybe we could just use the SWHS idea and keep the CaseStudy folders, but just include a readme that points to the correct repo?  For SWHS the readme.md is located at:

https://github.com/JacquesCarette/literate-scientific-software/tree/master/CaseStudies/swpcm

Going forward there will be less and less maintenance for the CaseStudies, and there are no dependencies at all from a compilation point of view.  My instinct is that we don't need submodules, but I'm willing to be convinced otherwise.

I've been collecting my thoughts as I write.  😄  I am okay with moving the CaseStudies out of the Drasil repo.  Rather than submodules though, I think we can just use the readme.md idea I just mentioned.

As far as the C code in the repo goes, I know the reason for it, and the ideal fix, but I don't know the best path to get there.  The reason for the code is that the Chipmunk example is bigger than the others.  Rather than code everything from scratch, we simply modified the original Chipmunk to match our simplified requirements.  This means that most of the code is Chipmunk code that wasn't written by an of our team.  What would be more helpful for Drasil (in my opinion) is a much simpler library, where we have written the code.  We cannot hope to use code generation to generate Chipmunk.  There is just too much going on in there.  We need a simpler physics simulator.

If we get another summer student on Chipmunk, I think they should start from the requirements for the design and implementation, and not reuse the existing library.  In hindsight, that was likely a mistake.

In the short term though, I don't want to delete the code that we have.  The code does work (or at least it did the last time I checked), and it can provide us with a benchmark for comparison with future code.  @JacquesCarette's idea to move the CaseStudies outside of Drasil would fix the problem of too much C code.  Down the road we can address the problem of how to make the game physics code more useful.

**Comment by JacquesCarette** [comment]
I was most definitely not suggesting that we delete anything.  I should have been clearer that I want to move things out of the Drasil repo, as it does not logically belong there.

I am perfectly happy with links. I should have been clearer that 'moving out' was the issue, and submodules was one potential solution. Probably should have made a comment rather than put it in the issue itself.

**Comment by smiths** [comment]
We should wait for @szymczdm's thoughts, but it seems like we are converging to removing the case studies.  Does it make more sense to create a separate repo for each, as in the SWHS example, or one Case Studies repo?  My initial thought is a separate repo for each, but since the amount of modification to the case studies is dropping off, this might divide things up too much.

**Comment by JacquesCarette** [comment]
I would think a single repo would suffice.  We could always add more case studies to it later, all in one convenient place.

**Comment by smiths** [comment]
Yes, I agree.  A single repo is fine, although I would like to continue to maintain SWHS as a separate repo.

**Comment by szymczdm** [comment]
Sorry I didn't respond until now, I seem to have accidentally archived the email chain for this issue (and was looking at the older issues until now). 

I think we should remove the case studies to their own repo (with the exception of SWHS which, if we're already maintaining it separately, shouldn't be a problem). It will also make the log a bit cleaner when we're adding case studies down the road.

Linking to the case study repository would be a necessary, I'd suggest right from the root README.

**Comment by smiths** [comment]
I think we are agreed to move the Case Studies out of the Drasil repo, into their own repo, with pointers in the Drasil repo to the Case Studies.  @JacquesCarette offered to create the external repo, but maybe it makes more sense if I do it, since the SWHS example is already under my GitHub user name?  It isn't a big deal either way.  @JacquesCarette, if you want me to create a Case Studies repo, you can assign this issue to me.  If you would rather do it, please go ahead.  😄 

A Case Studies repo would be nice for what we are doing right now with @halonazhao and @deviprasad135.  The issues that we create that involve changing the manual version of the case studies can be issues that exist in the case studies repo.

**Comment by JacquesCarette** [comment]
@smiths I think it makes sense for you to create this under your own name.

Eventually, we might want to look into creating a 'group' to own all of this. But that can wait.

**Comment by smiths** [comment]
The case studies have been moved to https://github.com/smiths/caseStudies.  Without much effort, I was able to keep the commit history for the new repo.  😄 

In commit d898c6bd I have removed the case studies and included a pointer to them in the README.md file.
