### ISSUE TITLE
Drasil MG - Level 3 modules

### ISSUE THREAD

**Issue by lmawarid** [JacquesCarette/literate-scientific-software#66]
I have some level 3 modules in my Module Guide, but it seems that the current Drasil implementation only supports two levels. For example, I have the children of the Shape Module:

![image](https://cloud.githubusercontent.com/assets/16506055/17633771/0b39cd26-609d-11e6-802b-548c95a327d3.png)

I am also unable to specify these modules as children of their parent module in the Drasil MG. In the original MG, that looks like this:

![image](https://cloud.githubusercontent.com/assets/16506055/17633810/3cbc9932-609d-11e6-81c2-9bd109125429.png)

**Comment by palmerst** [comment]
It should support level 3, but they are implemented as LaTeX paragraphs (this is the heading level below subsubsection).  They won't appear in the table of contents, but should still show up in the module hierarchy and module descriptions (I will add a redefinition so that they do later).  I just tested this and it works for me.

I will add support for children.

**Comment by lmawarid** [comment]
I see, I missed the fact that I could've nested them under Shape. The implementation has been updated now, and the paragraphs and table (module hierarchy) are working properly as you said.

**Comment by szymczdm** [comment]
Sounds like this one has been resolved, so I'm going to close it for the time being. If I'm wrong, please reopen it @palmerst (as I assume you have the best knowledge of this situation).
