### ISSUE TITLE
Summation breaks MIS/MG Generation

### ISSUE THREAD

**Issue by szymczdm** [JacquesCarette/literate-scientific-software#71]
I changed the way summation is handled (so now the bounds can be included), and upon testing it would up breaking the MIS/MG generation. I've put all changes into a branch (DanWB2<sup>1</sup>) but here's what I've gathered:

Making code doesn't work as there's no function for making summation code yet (this is obvious).

Creating the MIS ends up trying to perform a foldl1 on something that is empty, not sure exactly why this is happening, so if Steven could look at the code that would be fantastic.

--
<sup>1</sup>Named so because when I tried to stash from master and apply to DanWB it performed a merge which was just bad and I didn't want to waste time dealing with branches

**Comment by palmerst** [comment]
I used foldl1 to print the inputs, outputs and exceptions for each method in the MIS, which was seemingly a bad idea as it breaks with empty lists.  I switched the foldl1's to foldl so it handles empty lists now.  

The empty list was arising from an empty list of exceptions.  This is occurring because the denominator detection to set divide by zero exceptions currently only has patterns for -+*/^ in Expr's and doesn't detect correctly in the h_c definition with summation.

I pushed the fix to master so you can merge/rebase into your branch.
