### ISSUE TITLE
Clean up testing makefile

### ISSUE THREAD

**Issue by szymczdm** [JacquesCarette/literate-scientific-software#75]
The makefile created in e0df0be8 should be cleaned up to be more succinct. I'm sure there's a way to do it, I'm just not sure the exact means at this point in time. I do not think this is high priority right now, but as we get more examples this will become more necessary for quick and easy testing.

**Comment by smiths** [comment]
Hi Dan.  Your makefile will be a great help.  Unfortunately when I tried to run it I received an error message.  I switched to the DanWB2 branch (the Makefile doesn't seem to be in master) and ran make.  The output was as follows:

[24 of 53] Compiling Language.Drasil.TeX.Monad ( Language/Drasil/TeX/Monad.hs, dist/build/Language/Drasil/TeX/Monad.o )

Language/Drasil/TeX/Monad.hs:70:10:
    Not in scope: type constructor or class ‘Monoid’
    Perhaps you meant ‘Monad’ (imported from Prelude)
make: *** [swhs] Error 1

**Comment by smiths** [comment]
I verified that the problem was my version of ghci.  I compiled with version 8.0.1 without any error messages.

Dan, before we close this issue, can you please add an output at the end that summarizes whether the log files are empty or not.  Ideally, it would be good to highlight the ones that are not empty.  I had to manually check each log file to see that it was empty.  It would be nicer if I just got a message that told me that there were no problems.

**Comment by szymczdm** [comment]
Done as of commit 5ad1fa1aa7. There should now be a message stating whether or not the files match and which logs don't match.

**Comment by smiths** [comment]
Looks good.
