### ISSUE TITLE
heat transfer, thermal conductivity

### ISSUE THREAD

**Issue by JacquesCarette** [JacquesCarette/literate-scientific-software#77]
I was trying to unify two different units, both called `heat_transfer`.  One was kg/s^3/C and the other W/m^2/C -- which are equivalent units.  But they are 'different', in the sense of displaying differently.  So when I unify them, I get a test failure (yay!).

Thus I would like to pick one way to display them, and make that the expected result everywhere.  I vote for W/m^2/C.

Second, there's the problem of the name!  For example, at
http://www.engineeringtoolbox.com/conductive-heat-transfer-d_428.html
what we call `heat_transfer` is called `thermal_conductivity`.  And `heat_transfer` is just Watt.  Even more so, NIST http://physics.nist.gov/cuu/Units/units.html also calls that unit `thermal_conductivity`.

So I think we should change the name to agree with the standards.

I am assigning this to Spencer for the 'design' part, and to me to implement it.

**Comment by smiths** [comment]
I don't have a chance to look at the details right now, but my guess is that we need to be careful here.  Thermal conductivity and the heat transfer coefficient are similar, but not the same.  For one, thermal conductivity has units of W/(mK), while the heat transfer coefficient has units of W/(m^2K).  (The units are different!)  I think the problem might be that we are calling the heat transfer coefficient simply heat transfer.

**Comment by JacquesCarette** [comment]
This is why the issue was assigned to you, and I didn't just blindly go in and 'fix' it...  But I would like if we could resolve this quickly, as this is holding up some other changes that I would like to make.

**Comment by smiths** [comment]
Hi Jacques.  I agree with your choice to use W/m^2/C.  In looking over the Drasil code, I think the confusion came up because the name of the unit was heat_transfer.  You are correct that the concept of heat_transfer could be interpreted many different ways.  My suggestion is that we change the name to heat_transfer_coeff.  This makes it clear that the units are for the heat transfer coefficient, and not for some more general concept of heat transfer.  If you agree, we can create a separate issue to change the name.

**Comment by JacquesCarette** [comment]
Agreed.  So this Design is done (and implemented), up to the new issue of the name.
