### ISSUE TITLE
Clean up SSP example - Unique chunks

### ISSUE THREAD

**Issue by szymczdm** [JacquesCarette/literate-scientific-software#89]
Same reasoning as #88.

**Comment by szymczdm** [comment]
By "clean up" I mean removing as much duplication as we can, creating new combinators, etc. It will be an ongoing task over the summer, but we should get the first pass done soon.

**Comment by JacquesCarette** [comment]
See comments on #88, with Henry replaced by Nicholas.

**Comment by szymczdm** [comment]
Specific goal of this pass: remove all duplication of concepts so that each comes from a single unique source.

**Comment by njericha** [comment]
All concepts in my Defs.hs and my units in Units.hs are super specific to my example so there is no duplication. I cannot move any of my units to Concepts\physics.hs because they are not general enough. I could make a SolidMechanics.hs in concepts and I could move the more "general" stress/strain/friction terms in there?

**Comment by JacquesCarette** [comment]
@njericha Yes, I think that is worthwhile.  And indeed, exactly as you say: only the "general" ones relating to solid mechanics.

**Comment by njericha** [comment]
finished putting all four "general" terms into a new file `concepts\SolidMechanics.hs` 853cd8bddb35642abe6d71472a3db17ae2b614af 
Before I close, the last possibly shared concept SSP uses is "generic 1D force" as opposed to just "force" from `concepts\Physics.hs`. Should I update SSP to use the general "force" or create a new term for SSP that uses the general "force"

**Comment by smiths** [comment]
Hello Nicholas.  I'm not sure what generic is referring to.  I don't think this is something to highlight.  However, the distinction between 1D, 2D and 3D is relevant at times.  In some cases we discuss a force vector, while in other cases we can simplify things to a scalar representing the force.  The scalar is still actually a vector, but because of the assumptions made we don't make this explicit.

I don't think we should split the concept of force between Physics and Solid Mechanics.  Forces exist in physical problems other than solid mechanics, so my vote would be to put the concept of force there.  It would be neat if the concept was always a force vector and we automatically simplified it in contexts where this is possible.  I think this would be beyond what Drasil can currently do, so having the concept of a force and a separate concept of a force vector might be the best approach.  Hopefully we don't need to have separate concepts for 2D and 3D vectors.

**Comment by njericha** [comment]
Thanks, @smiths . I was not sure what SSP meant by "generic" either. For now I will use "force" as defined in Concepts and if needed, add a vector version later.

**Comment by smiths** [comment]
Sounds good.

**Comment by njericha** [comment]
Fixed 8911d3d039d2704d09addc5dde2aac86563b34e3
