### ISSUE TITLE
Fix table of symbols chunks to use new CDefns

### ISSUE THREAD

**Issue by szymczdm** [JacquesCarette/literate-scientific-software#95]
This has actually turned out to be a bigger issue than expected. Simply parameterizing the table of symbols function isn't enough, but it is revealing other issues. Namely: the way the chunks leading up to MUChunk are set up right now, they are not an instance of ConceptDefinition(').

I'm not sure what the best approach to get this working would be. Surface level it looks like I'll need to introduce a new "chain" of chunk types built off of DefinedTerms before the ToS fix will work (essentially rebuild all of the current chunks with the new split), but that seems like it would add a lot of bloat that should be possible to avoid. The most obvious bloat would be when it comes to combining the MDefinedConcepts with MUChunks. I'm going to look deeper and see if a better solution presents itself.

I've committed and pushed the table of symbols parameterization, but it's mostly a hack that was intended to get things working. Not being able to hack this together seems like a good sign (good infrastructure), but the aforementioned bloat creeping in seems like a bad sign. On the other hand, it might fix itself if/when we move away from the "simple" concept chunks and strictly use the defined concepts.

**Comment by JacquesCarette** [comment]
I agree, we probably need to sit down, and rethink our chunks.  I think the ones expressed via the typeclasses are fine, but our current implementations (aka data-structures) might need rethinking.

That said, your implementation does point out the underlying issue: when asking for a table of symbols, do we want a table of definitions, or a table of terms?  You have implemented a fallback strategy for tables of definitions.

To me, this says that we probably want 3 things: table of definitions, terms, and mixed (definitions when available, otherwise terms).  A recipe should be able to choose which it wants.  Which probably means that we should have, for now, a data-type enumerating these 3 choices.  This is a good Haskell way of doing things, but sub-optimal for Drasil, as it bakes in too much Drasil-oriented knowledge in Haskell.  But until we can see a better way, I think that's probably the best we can do. 

Then if you choose a recipe that wants definitions and you don't have definitions for all your terms, it won't compile.

**Comment by szymczdm** [comment]
I'm fairly certain this (specific) issue is now no longer a concern as CDefn has been deprecated and no longer exists. As such, I'm closing this issue.
