### ISSUE TITLE
Implement newly redesigned chunk hierarchy

### ISSUE THREAD

**Issue by szymczdm** [JacquesCarette/literate-scientific-software#97]
![img_20161214_170646](https://cloud.githubusercontent.com/assets/235140/21275274/0a3b23ba-c39a-11e6-8ac2-b3dd40f8df28.jpg)

The attached photo shows the results of Jacques and my design meeting earlier this week (I'll add a cleaned up version soon as a comment). We have concluded: 
  1. The current design of our hierarchy convolutes "is-a" and "has-a" relationships, 
  2. many things need to be renamed for the sake of clarity, and 
  3. some information was clearly missing (ie. the type of the space that we are working in).

This may end up being a milestone moreso than a single issue, as there are many small changes to be made, but for now I'll write up everything here and we can open/close issues as necessary.

First, minor changes: 
  - "name" (of Chunk) should now be called "id"
  - "descr" (of Concept) should now be "term"
  - "cdefn" (of DefinedConcept) should now be "defn"
  - "Concept" should be changed to "NamedIdea"
  - "DefinedConcept" should be changed to "Concept"

Second, less minor changes:
  - New "SymbolForm" replaces current "Quantity" as a chunk with some symbolic representation
  - "Quantity" now has a new "typ" field representing the space said quantity exists within
  - "Quantity" will also represent (possibly) "dimensioned" things. ie. it "may contain" a Unit (retrieved through "get-unit"
  - "Quantity" no longer requires a SymbolForm; it "may have" one.

The main overall change to get from this is that now we are enacting strict "is-a" relationships in the Chunk hierarchy, instead of our previous mash of "is-a" and "has-a". As an example, our current "Quantity" class can be an instance of both "DefinedConcept" and "Unit" (meaning it *is* both), but that is conceptually incorrect as it should be a DefinedConcept which *may have* a unit.

@JacquesCarette If I've missed anything, please let me know, and if I remember anything else I will add it below.

**Comment by szymczdm** [comment]
Re-drawn version of the image here.
![hierarchy-redesign](https://cloud.githubusercontent.com/assets/235140/21276632/519ece0e-c3a0-11e6-9b5c-5102a1176bfc.png)

Also note: I forgot to mention the relaxation of constraints on what used to be Quantity (new "SymbolForm") such that the minimal requirement is that it is also an instance of Chunk (as opposed to Concept).

**Comment by JacquesCarette** [comment]
Yes, this does capture our discussion.

**Comment by smiths** [comment]
The picture looks great!  I can see that I definitely did miss a good meeting.  I really like seeing the type information in there.

I'm a bit confused though.  I think we should spend some time on this during our meeting on Monday (Dec 19).  Some things we might discuss are as follows:

The sample id name given above isn't meaningful.  Is that just because it is a quick example, or are these ids that are tracked by the system, and thus not intended to be meaningful?  How complex can we get with the type of Quantity?  Can it be a function, like R -> R?  Is there any case where we would have a symbol chunk but no further information on that chunk?  I'm sure I'll get used to it, but on first glance having the SymbolForm all by itself on the right side looks odd.

**Comment by JacquesCarette** [comment]
You do have to remember that the above is not a set of *data structures*, but a set of ideas/concepts.  We have (many) data structures which 'implement' the above ideas.  Would a data-structure that just is a symbol be useful?  Not really.  

What is missing from the above [not because it hasn't been transcribed, but because it doesn't exist!] are the software-related concepts.  They have started to exist (as data-structures), but not yet as concepts.  That needs fixed.  That will include another "may have" link to SymbolForm.

The 'id' is meant to be 100% internal.  Which is why Dan is suggesting we change it from 'name' to 'id', as 'name' confused people into thinking it was supposed to be meaningful.  Of course, it is better if internal names are good too, but that's a different matter.

We have not designed anything about the "type system" to be tracked by quantities.  It just became obvious that it was needed.  Now we get to see what we actually use.

**Comment by smiths** [comment]
Thank you Jacques.  Your explanations are very helpful.  I think I was confusing this with the idea of a data structure.  I would still like to talk about this further on Monday, maybe starting with the difference between a concept and a data structure.  :-)

**Comment by JacquesCarette** [comment]
concept is to module signature as  data structure is to module implementation.

**Comment by szymczdm** [comment]
I believe this is now complete, as the unnecessary classes have been removed and those we needed to keep have been updated.
